### PR TITLE
Fix responsive behavior of SoSpecial carousel items across screen sizes

### LINKED ISSUE #7305: Fixing slider on small devices
### Current Behavior
The slider is not adjusting the number of items to show on small devices, causing the child items to shrink.
The slider is can be fund here https://layer5.io/projects

Here is the screenshot

Image

### Desired Situation
Adapt the number of items inside the slider base on the screen (responsiveness)

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Katotodan**
**Description**
This PR fixes a rendering issue in the SoSpecial carousel where slider items were shrinking on small devices.
The root cause was related to Gatsby’s SSR behavior: the slider was initially rendered on the server without access to viewport-dependent  values used in the slider settings (inside settings > responsive array), causing react-slick to compute incorrect dimensions.
To fix this, SSR rendering was kind of disabled for this specific component, and the slider settings are now adjusted programmatically on the client based on the current screen size. This ensures consistent and stable rendering across all breakpoints.

This PR fixes #7305

Here is the picture before 
PHOTO-2025-12-29-01-42-42

After
Screenshot 2025-12-29 at 21 09 08

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit f83e56c9be19ae99b76a66af424a74a27a08caf7 at: https://6952c83dfa81b7936b9b64b4--layer5.netlify.app

**Review by kishore08-07 — COMMENTED** [review]
@Katotodan 
Use the **Related Resources** section on https://layer5.io/solutions/platform-engineering as the reference for the expected behavior.

**Comment by l5io** [comment]
🚀 Preview for commit 013f035e45330868ac9afefaf93d70deb360c8de at: https://69550b75eb2fb35344b02635--layer5.netlify.app

**Comment by Katotodan** [comment]
@kishore08-07 Can you take a look please?

**Comment by l5io** [comment]
🚀 Preview for commit 8c1d98d2f378d3802e6c963caeafa6b0a70438ae at: https://69552fdd914961d5ff8e4ef8--layer5.netlify.app

**Comment by Katotodan** [comment]
@kishore08-07 I have done so, please review

File: src/sections/Home/So-Special-Section/so-special-style.js [hunk 1]
```diff
@@ -104,17 +104,19 @@ const SoSpecialWrapper = styled.div`
...
           .gatsby-image-wrapper, .old-gatsby-image-wrapper{
               height:100%;
           }
           img{
-            height: inherit;
+            height: 17rem;
             display: block;
             text-align: center;
             margin: auto;
+            object-fit: fill !important;
```
Comment (kishore08-07) [inline src/sections/Home/So-Special-Section/so-special-style.js:118]: revert !important.

Comment (Katotodan) [reply src/sections/Home/So-Special-Section/so-special-style.js:118]: @kishore08-07 The Image has object-fit set to cover by default.
That was done inside src/components/image.js
```
import { GatsbyImage } from "gatsby-plugin-image";

const Image = ({ childImageSharp, extension, publicURL, alt, imgStyle, ...rest }) => {

  if (!childImageSharp && extension === "svg") {
    return (
      <div className="old-gatsby-image-wrapper" style={{ width: "100%", height: "auto" }}>
        <img
          src={publicURL}
          alt={alt || "Blog image"}
          width="100%"
          height="auto"
          style={{
            objectFit: imgStyle?.objectFit || "cover",
            ...imgStyle
          }}
        />
      </div>
    );
  }

  return <GatsbyImage
    key={publicURL}
    image={childImageSharp?.gatsbyImageData}
    alt={alt || "Blog image"}
    style={{
      objectFit: imgStyle?.objectFit || "cover",
    }}
    {...rest}
  />;
};

export default Image;
```
Removing that !important on that line of code is making the default one to win. And the images are not showing well anymore after removing that !important. What do you think?

Comment (Katotodan) [reply src/sections/Home/So-Special-Section/so-special-style.js:118]: Mr. @kishore08-07 , what is your thought? And seems like Gatsby generate "img" with inline styles, among them object-fit set to cover. So removing that !important make Gatsby image inline style to win.

Comment (kishore08-07) [reply src/sections/Home/So-Special-Section/so-special-style.js:118]: since the Image component uses object-fit: cover by default, the !important makes sense here.

Comment (Katotodan) [reply src/sections/Home/So-Special-Section/so-special-style.js:118]: @kishore08-07 thank you for the review

**Comment by l5io** [comment]
🚀 Preview for commit 14617ca7f656119950f9865e0ce8b939915cc085 at: https://695bd248842366cbd115c499--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 225289d06bd20d6936d13eb17be9df955fc3f099 at: https://695d31102932d09ca67b6f85--layer5.netlify.app

**Comment by Katotodan** [comment]
@Rajesh-Nagarajan-11 thanks for reviewing my PR!
Please let me know if there’s anything else needed from my side.

**Comment by l5io** [comment]
🚀 Preview for commit d37f3844479b462eb367d2f62c49f7e7bc814030 at: https://6961020d559073a7cc5d638f--layer5.netlify.app

**Comment by kishore08-07** [comment]
@Rajesh-Nagarajan-11 This PR is awaiting merge.
