### PR TITLE
fix: updated broken pricing page and documentation links #7348

### LINKED ISSUE #7348: Broken Links on the Pricing Page
### Description
On this page https://layer5.io/pricing 
Links like : https://docs.layer5.io/kanvas/operator/operator-views/
- https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

- https://github.com/layer5io/layer5/blob/master/src/pages/pricing.js
### Expected Behavior
all should be working

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Joiejoie1**
**Description**

This PR fixes #7348

**Notes for Reviewers**

Logic & Verification: While the local build environment had memory constraints, I verified the fixes by:

Code Traceability: Tracing the code to src/sections/Pricing/openSource.js to ensure the internal routing path is correct.

File Verification: Confirming the existence of the destination file at src/pages/community/open-source-program.js.

Query Refactoring: Fixing the GitHub search query parameters to ensure the "Help Wanted" link works correctly for new contributors.

Documentation Link Update: Updated the Kanvas Operator link to the current live URL at /kanvas/designer/operator-views.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 

Logic:
While the local build environment had memory constraints, I verified the fixes by:

Tracing the code to src/sections/Pricing/openSource.js.

Confirming the existence of the destination file at src/pages/community/open-source-program.js.

Fixing the GitHub search query parameters to ensure the "Help Wanted" link works for new contributors.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9b5100fbc25258ebb6e26fb96a9e1bd78bf3c184 at: https://697391aadb70c39dccedc6e1--layer5.netlify.app

**Comment by Bhumikagarggg** [comment]
@Joiejoie1 Thank you for your contribution! Let's discuss this during the website call today at 6:30 PM IST | 7 AM CST Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would 🙂

**Comment by Joiejoie1** [comment]
> @Joiejoie1 Thank you for your contribution! Let's discuss this during the website call today at 6:30 PM IST | 7 AM CST Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would 🙂
Thanks I will @Bhumikagarggg

**Comment by lekaf974** [comment]
related to #7348

**Comment by Bhumikagarggg** [comment]
@Joiejoie1 please Update your PR description  [x] remove space like i did it.
Thank you

**Comment by Joiejoie1** [comment]
> @Joiejoie1 please Update your PR description **The PR fixes #7348** and [x] remove space like i did it. Thank you

Thanks @Bhumikagarggg

**Comment by Joiejoie1** [comment]
> > @Joiejoie1 please Update your PR description **The PR fixes #7348** and [x] remove space like i did it. Thank you
> 
> Thanks @Bhumikagarggg

Done @Bhumikagarggg 

Let me know if there is anything else I have to do.

**Comment by CodexRaunak** [comment]
The build issue will be fixed by https://github.com/layer5io/layer5/pull/7376

**Comment by saurabhraghuvanshii** [comment]
@Joiejoie1 Please also update FAQ broken link which provided in issue description

**Comment by l5io** [comment]
🚀 Preview for commit 4c7f802abc6f7995feb3a9a24e4a602ec92d75d2 at: https://697798b823c88b1066fc1035--layer5.netlify.app

**Comment by Joiejoie1** [comment]
> @Joiejoie1 Please also update FAQ broken link which provided in issue description

Duly noted @saurabhraghuvanshii

**Comment by l5io** [comment]
🚀 Preview for commit be4c7a259f53c9ffab038d114dfda2b8f67d2380 at: https://6977ae07e056a300d29e39ba--layer5.netlify.app

**Comment by Rajesh-Nagarajan-11** [comment]
@Joiejoie1  Kindly Sign off the commits

**Comment by l5io** [comment]
🚀 Preview for commit 2c3e12a4225d859e32c8eaa67c33c5e94ef87f5e at: https://6978925a622163ff85b794e5--layer5.netlify.app

**Comment by Joiejoie1** [comment]
> @Joiejoie1 Kindly Sign off the commits

Thanks @saurabhraghuvanshii  . I'll do that.

File: src/assets/data/faq/index.js [hunk 1]
```diff
@@ -478,7 +478,7 @@ const data = {
     {
       question: "How often does Layer5 offer internships?",
       category: "Careers",
-      category: "Internships",
+      subcategory: "Internships",
       answer: [
```
Comment (saurabhraghuvanshii) [inline src/assets/data/faq/index.js:482]: @Joiejoie1 update help wanted button with layer5 issues also

**Comment by l5io** [comment]
🚀 Preview for commit a7065b567d177871c77f88544a62ef291fe8a76e at: https://6978ce6a15dfbc33f0e2db5c--layer5.netlify.app

File: src/assets/data/faq/index.js [hunk 2]
```diff
@@ -478,17 +478,17 @@ const data = {
...
         "Continuously. Layer5 has internships starting and stopping frequently. Some internships rigidly start and stop on particular dates, while other internships offered start as a batch of candidates show collective readiness. We work with individuals to align the timings of the internship with other activities in their life.",
       ],
-      link: "https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+",
+      link: "https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22",
```
Comment (saurabhraghuvanshii) [inline src/assets/data/faq/index.js]:
```suggestion
      link: "https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+label%3A%22help+wanted%22+%28org%3Alayer5io+OR+org%3Ameshery+OR+user%3Aservice-mesh-patterns+OR+user%3Aservice-mesh-performance%29",
```

Comment (saurabhraghuvanshii) [reply src/assets/data/faq/index.js]: @Joiejoie1 correct form of link

**Comment by Joiejoie1** [comment]
Got it! I'll update the link to use the correct search syntax with the OR operators and user prefixes as suggested.

**Comment by saurabhraghuvanshii** [comment]
> Got it! I'll update the link to use the correct search syntax with the OR operators and user prefixes as suggested.
 
Already done!!

**Comment by l5io** [comment]
🚀 Preview for commit 4f38b011e1c8323c89ab658a561a74755233b3e8 at: https://6978dd3968751400aa3fa062--layer5.netlify.app

File: src/sections/Pricing/openSource.js [hunk 3]
```diff
@@ -12,7 +12,7 @@ const OpenSourceBanner = () => {
             We 💚 open source and are proud to sponsor your free use of our tools.
           </p>
         </div>
-        <Button $primary title="Open Source Pricing" $url="/pricing/open-source-program"><BsArrowUpRight size={21} className="icon-left" /></Button>
+        <Button $primary title="Open Source Pricing" $url="/community/open-source-program"><BsArrowUpRight size={21} className="icon-left" /></Button>
```
Comment (saurabhraghuvanshii) [inline src/sections/Pricing/openSource.js]:
```suggestion
        <Button $primary title="Open Source Pricing" $url="/pricing/open-source-program"><BsArrowUpRight size={21} className="icon-left" /></Button>
```

**Comment by saurabhraghuvanshii** [comment]
Thanks @Joiejoie1 lgtm!!

**Comment by Joiejoie1** [comment]
> Thanks @Joiejoie1 lgtm!!

Sure,
Updated the FAQ with the suggested GitHub search syntax and corrected the duplicate category. Rebased and signed off! @saurabhraghuvanshii
