### PR TITLE
Fix #4305 - Buttons in hero banner redirect to a bad url & 404 after Meshery page is reloaded

### LINKED ISSUE #4305: Redirected to wrong page
### Description

On [meshery](https://layer5.io/cloud-native-management/meshery) page ,once a user reloads the page and click on `How Meshery Works` button it  redirects the user to the page  https://layer5.io/cloud-native-management/meshery.html/operating-service-meshes  instead of  https://layer5.io/cloud-native-management/meshery/operating-service-meshes. 

Similarly once a user clicks on `Run Meshery` button ,it directs him to the page  https://layer5.io/cloud-native-management/meshery.html/getting-started  instead of  https://layer5.io/cloud-native-management/meshery/getting-started .

Note that this behaviour doesn't happens the first time a user visits the page. It only happens when once the page is being reloaded. Below is a video describing the issue :

[Screencast from 29-05-23 02:23:11 AM IST.webm](https://github.com/layer5io/layer5/assets/114604338/16fda1ce-c63e-4329-acae-08094b528dfb)

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by randychilau**
**Description**

This PR fixes #4305. 

before:

[redirect error](https://github.com/layer5io/layer5/assets//114604338/241587137-16fda1ce-c63e-4329-acae-08094b528dfb)

after:

[issue4305fix.webm](https://github.com/layer5io/layer5/assets/90356410/86968db6-c5e6-4e8b-b8e0-b9e2a252d738)

This PR also clears a number of dev console warnings on related pages (in detail below).

---

**Notes for Reviewers**

Possible explanation for fix: The button url links were relative with "./" and I believe the "." somehow made the link created for the buttons originate from the **file link path** instead of the browser displayed link path.

So instead of getting:
`https://layer5.io/cloud-native-management/meshery/operating-service-meshes`

the result was (note: the `.html`):
`https://layer5.io/cloud-native-management/meshery.html/operating-service-meshes`

Unfortunately as of this PR, I couldn't find documentation supporting this possibility.

---

This PR also clears the following dev warnings on these pages:

`https://layer5.io/cloud-native-management/meshery/operating-service-meshes`
>Warning: Cannot update a component (`HowItWorks`) while rendering a different component (`Feature`). To locate the bad setState() call inside `Feature`

---

`https://layer5.io/cloud-native-management/meshery`
>Warning: Expected server HTML to contain a matching \<tr\> in \<table\>.

>Warning: validateDOMNesting(...): \<tr\> cannot appear as a child of \<tabl\e>. Add a \<tbody\>, \<thead\> or \<tfoot\> to your code to match the DOM tree generated by the browser.

>External link https://docs.meshery.io/extensibility was detected in a Link component. Use the Link component only for internal links.

note: cleared this warning on other pages with the same code

---

`https://layer5.io/cloud-native-management/meshmap`
>Warning: Cannot update a component (`DesignerFeatures`) while rendering a different component (`Feature`).

>Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()

>Warning: React has detected a change in the order of Hooks called by DesignerFeatures. This will lead to bugs and errors if not fixed.

>Warning: Use the `defaultValue` or `value` props on \<select\> instead of setting `selected` on \<option\>.

---

`https://layer5.io/learn/learning-paths`
>Warning: Expected server HTML to contain a matching text node for "
" in \<pre\>.

cheers!

---

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 3b78fc68fcd660f11d17abc44f9328bdf7a44a5a at: https://6476e592fc486b689f1499e5--layer5.netlify.app

File: src/components/Terminal/index.js [hunk 1]
```diff
@@ -57,15 +57,18 @@ const Terminal = ({ lines, title, noScroll }) => {
           <div className="code-wrapper">
             {lines && lines.map((line, index) => (
               <Fragment key={index}>
-                <pre className={`${line.short ? "short" : ""} ${line.color ? line.color : "blue"}`} >
-                  {line.indent &&
+                {line.code === "\n"
+                  ? <pre>{line.code}</pre>
+                  : <pre className={`${line.short ? "short" : ""} ${line.color ? line.color : "blue"}`} >
+                    {line.indent &&
```
Comment (Nikhil-Ladha) [inline src/components/Terminal/index.js:63]: Why this change?

File: src/sections/Meshmap/FeaturesSection/useGsapTimeline.js [hunk 2]
```diff
@@ -1,23 +1,18 @@
...
 gsap.registerPlugin(ScrollTrigger);
 
 const useGsapTimeline = ({ trigger, featureContainerName,yPercent }) => {
 
-  const hasMounted = useHasMounted();
-
   const useIsomorphicLayoutEffect =
-  hasMounted ? useLayoutEffect : useEffect;
-
+  typeof window !== "undefined" ? useLayoutEffect : useEffect;
```
[the remark this answers is not in the document]
Comment (randychilau) [reply src/sections/Meshmap/FeaturesSection/useGsapTimeline.js:10]: Hi @Nikhil-Ladha,

Hope all is well.

There was a console dev warning:

>Warning: React has detected a change in the order of Hooks called by DesignerFeatures. This will lead to bugs and errors if not fixed...

image

that was triggering when the DesignerFeatures. VisualizerFeatures, and CollaboratorFeatures components loaded. I followed it to this hook `useGsapTimeline.js` and noticed that I had earlier replaced the ` typeof window !== "undefined" ` with the `useHasMounted` method. 

After further examination, I realized the [`useHasMounted` method](https://www.joshwcomeau.com/react/the-perils-of-rehydration/#the-solution-9) is meant to replace `typeof window !== "undefined"` to make sure **content** in the "hydrated app matches the original HTML", and that I incorrectly used it in this hook (causing the dev warning).

I reverted to the original implementation `typeof window !== "undefined" ? useLayoutEffect : useEffect;` and the dev warning was cleared.

Thanks!

**Comment by l5io** [comment]
🚀 Preview for commit a1f1d29e19e8cdb43b9319952caf8d7c5ae871d7 at: https://647a31c54a89e94186b725db--layer5.netlify.app

File: src/components/Terminal/index.js (hunk 1 above)
Comment (randychilau) [reply src/components/Terminal/index.js]: Hi @Nikhil-Ladha,

Thanks for highlighting this. I forgot to include this console dev warning in the `Notes` section. It was occurring in this component `src/components/Learn-Components/what-await-section/index.js`.

>Warning: Expected server HTML to contain a matching text node for "
" in <pre>.
image

When I re-examined this dev warning, I realized that while my changes did clear the dev warning, it was not a correct method. After looking into the issue more, I saw how the `"\n"` was handled in this component `src/sections/Meshery/Meshery-terminal/index.js`, by using a `" "` instead.

I reverted my changes on `src/components/Terminal/index.js` and then made the change to `" "` on `src/components/Learn-Components/what-await-section/index.js` and it cleared the warning. 

I also made changes to another similar usage of "\n" in this component `src/sections/Meshery/Meshery-features/index.js` (even though it was not triggering an error for some reason).

Thanks Nikhil!

**Review by Nikhil-Ladha — APPROVED** [review]
