### PR TITLE
fix links of learning-paths

### LINKED ISSUE #7193: Broken links in Mastering Meshery Learning Path
:help-wanted: HELP NEEDED: broken link - <https://layer5.io/learn/learning-paths/mastering-meshery/introduction-to-meshery.html/meshery/deploying-meshery-designs>

All Learning Path course links are redirecting to incorrect URLs. Please review and fix the links for each course and chapter.
Reference: https://layer5.io/learn/learning-paths

[Slack Message](https://mesheryio.slack.com/archives/C015QJKUMPU/p1764700911269159)

### PR DESCRIPTION
**Pull request by saurabhraghuvanshii**
**Description**

This PR fixes #7193 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit d1dfe3b60181f13ede5ea71df916e068adfc02e8 at: https://692f79147a399418b92d4c35--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f8d6fba2d9c665fd0abe6f4dc8c440408d8ce8e0 at: https://692f80b3e2edd3ff44943476--layer5.netlify.app

**Comment by leecalcote** [comment]
Switched from backtick to double quotes.

**Comment by leecalcote** [comment]
Awaiting re-run of lint checker...

**Comment by l5io** [comment]
🚀 Preview for commit f502c33a72498c1192240905624fb6aae08c2a94 at: https://692fc31681627983719bbb50--layer5.netlify.app

File: src/sections/Learn-Layer5/Course-Overview/index.js [hunk 1]
```diff
@@ -113,20 +113,27 @@ const CourseOverview = ({ course, chapters, serviceMeshesList, children }) => {
...
-                  chapter={getChapterTitle(item, chapters)}
-                />
-              </Link>
-            ))}
+            {course.frontmatter.toc.map((item, index) => {
+              const chapterNode = getChapterTitle(item, chapters);
+              return (
+                <Link
+                  key={index}
+                  to={chapterNode ? "/${chapterNode.fields.slug}" : "#"}
```
Comment (saurabhraghuvanshii) [inline src/sections/Learn-Layer5/Course-Overview/index.js:121]: this was breaking chapter overview https://layer5.io/$%7BchapterNode.fields.slug%7D
