### PR TITLE
fix: pricing buttons

### LINKED ISSUE #6558: non functional buttons on pricing page
### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Description**

This PR fixes #6558
- remove hardcoded plans data from the Products page and use the dynamic data used on the Pricing page.
- fix the buttons on the plan cards to point to their corresponding subscription pages.
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9c1b9458426e0ca1d23eac63aa6f612ec20745c5 at: https://68509a6d4d2d8223c43f7165--layer5.netlify.app

File: src/components/PlanCard/index.js [hunk 1]
```diff
@@ -3,19 +3,20 @@ import Button from "../../reusecore/Button";
...
+const PlanCard = ({ planData , isYearly }) => {
 
-  const openModal = () => setModalIsOpen(true);
-  const closeModal = () => setModalIsOpen(false);
 
   if (!planData || !Array.isArray(planData) || planData.length === 0) {
     return <div>No plan data available</div>;
   }
+  const planLink = {
+    "Personal": "https://kanvas.new",
```
Comment (vishalvivekm) [inline src/components/PlanCard/index.js]:
```suggestion
    "Personal": "https://cloud.layer5.io/account/plans",
```
```suggestion
    "Personal": "https://kanvas.new",
```

**Comment by l5io** [comment]
🚀 Preview for commit cad4fcad1cd5f186947079b134d63cf5ee6aa475 at: https://6850a5860f945448409a9fe4--layer5.netlify.app
