### PR TITLE
fix url conflict for members profiles

### LINKED ISSUE #6381: Bug: member slug collision might cause URL conflict
### Current Behavior

Currenlty, two community members have same name `yash sharma`: 
- https://layer5.io/community/members/yash
- https://layer5.io/community/members/yash-sharma

To avoid a URL conflict, one of the profiles uses only the first name (`yash`), which is not ideal. We want every member to have their full name represented in their index.mdx file (e.g., `collection/members/yash` should have full name).

### Desired Situation

We should ensure:
- All members can use their full names without risking a slug/URL collision.
- URLs remain unique and consistent even when names are identical:
    - `community/members/yash-sharma`
    - `community/members/yash-sharma-2`

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Description**

This PR fixes #6381
- adds support for optional `permalink` in member frontmatter to prevent slug collisions and ensure unique, readable URLs for profiles with the same name.
- updates the `_member_profile_template` file with this new field
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit e3ac1f6c2fe02dc9bcd1195cd3cfd6c685c8d7bc at: https://67fd178ba012926e873b7082--layer5.netlify.app

File: gatsby-node.js [hunk 1]
```diff
@@ -864,7 +865,8 @@ exports.onCreateNode = ({ node, actions, getNode }) => {
             break;
           case "members":
             if (node.frontmatter.published)
-              slug = `/community/members/${slugify(node.frontmatter.name)}`;
+              slug = `/community/members/${node.frontmatter.permalink ?? slugify(node.frontmatter.name)}`;
+              console.log(slug);
```
Comment (vishalvivekm) [inline gatsby-node.js:869]:
```suggestion
```

**Comment by l5io** [comment]
🚀 Preview for commit 675e7ede448edde6910a0bf4e385f5bfb1167707 at: https://67fd27b960a4acd087972ef6--layer5.netlify.app
