### PR TITLE
fix graphql error

### LINKED ISSUE #7556: Fix Graphql build error
### Description
On running `LITE_BUILD_PROFILE=content make site`

you get this error 
GraphQLError: Field "dateForSort" is not defined by type "MdxFieldsSortInput".

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by saurabhraghuvanshii**
**Description**

- Gatsby builds GraphQL input types (like MdxFieldsSortInput) from fields it sees during schema inference.

- In lightweight build profile, blog nodes are excluded.

- If dateForSort is only created for blog nodes, Gatsby never sees that field in this build.
- Then any query that says sort: { fields: { dateForSort: DESC } } fails at compile time with: Field "dateForSort" is not defined by type "MdxFieldsSortInput".

This PR fixes #7556

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: gatsby-node.js [hunk 1]
```diff
@@ -863,23 +863,20 @@ exports.onCreateNode = ({ node, actions, getNode }) => {
     value: collection,
   });
 
-  // Normalize blog date to ISO string for stable sort order across build environments (fixes production blog order)
-  if (collection === "blog") {
```
Comment (leecalcote) [inline gatsby-node.js:886]: Why not just removing this condition? Why does the rest of the script need to change? You have not offered any description justifying the change.

**Comment by l5io** [comment]
🚀 Preview for commit c2418af915cb7bff09304d8953a78da01b51d2dd at: https://69c451c0e951a4b02b933838--layer5.netlify.app

File: gatsby-node.js (hunk 1 above)
Comment (saurabhraghuvanshii) [reply gatsby-node.js:886]: I didn’t change the script—only removed the condition. The rest are lint-related changes after removing that condition.

**Comment by l5io** [comment]
🚀 Preview for commit b1692070c5350fe10ee0f7e92d2ec4e8d5ddc05e at: https://69c45b01177babc5f652cb59--layer5.netlify.app

File: gatsby-node.js (hunk 1 above)
Comment (leecalcote) [reply gatsby-node.js:886]: We keep running into this. Stop your linter from making all these changes.

**Review by leecalcote — APPROVED** [review]
