### PR TITLE
[Fix Layer5 GitHub Process] Convert contents to markdown

### LINKED ISSUE #5065: [Layer5 GitHub Process] Convert contents to markdown
### Current Behavior
The [Layer5 GitHub Process](https://docs.google.com/document/d/1FzX-C_xy9hZ3Eu9dcCE0unhFV5LRUrb5YLn_MGYuG6Y/edit) is currently in the form of a Google document.

### Desired Situation
Convert the Google document content to markdown and  add it to the Community Handbook

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by sandramsc**
**Description**

This PR fixes #5065 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9fc4ec3382eb3fc4ba5c3092edfec81bac6c765e at: https://6537493df10f492104dfba98--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b49e8a7f26ed87094829cbe8b271e9693a1d639d at: https://65374ee31e1ac81c3a4dc275--layer5.netlify.app

File: src/components/handbook-navigation/content.js [hunk 1]
```diff
@@ -13,5 +13,6 @@ export const content = [
   { id: 11, link: "/community/handbook/connect-with-us", text: "Connect with us" },
   { id: 12, link: "/community/handbook/code-of-conduct", text: "Code of Conduct" },
   { id: 13, link: "/community/handbook/security-vulnerabilities", text: "Security Vulnerabilities" },
-  { id: 14, link: "/community/handbook/faq", text: "FAQs" },
+  { id: 14, link: "/community/handbook/github-process", text: "GitHub Process" },
```
Comment (leecalcote) [inline src/components/handbook-navigation/content.js:16]: Side note: Tis a shame that the handbook content is manually tracked in this way - a potential enhancement at some point.

**Comment by leecalcote** [comment]
Yay! 😄

File: src/sections/Community/Handbook/github-process.js [hunk 2]
```diff
@@ -0,0 +1,463 @@
...
+        <h1>GitHub Process</h1>
+      </div>
+      <TOC />
+      <div className="page-section">
+        <Container>
+          <div className="content">
+            <h2>Issue and PR Labels and Templates, Bots</h2><br/>
+            <h3><strong>Overview</strong></h3><br />
+            <p>The Layer5 GitHub Process emphasizes consistent pull requests and issue labels to streamline continuous integration and reduce overhead across the growing repository collection.</p>
+            <p>The number of repositories under the “Layer5io” organization is growing. In order to ensure consistency across the repositories and to decrease the time it takes for a continuous integration (GitHub Actions) to execute, consistent use of pull request and issue labels will aid in the reduction of overhead.</p>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:20]: Right on. Also, worth noting: the Layer5 community spans five GitHub organizations - https://layer5.io/community/handbook/repository-overview

File: src/sections/Community/Handbook/github-process.js [hunk 3]
```diff
@@ -0,0 +1,463 @@
...
+
+            <h3>Issue and Pull Request Templates</h3>
+            <p>Layer5 uses issue and pull request templates. See the .github folder in any repo.</p>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:23]:
```suggestion
            <p>Layer5 uses issue and pull request templates. See the `.github` folder in any repo for examples.</p>
```

File: src/sections/Community/Handbook/github-process.js [hunk 4]
```diff
@@ -0,0 +1,463 @@
...
+                  <td>#eeeeee</td>
+                </tr>
+                <tr>
+                  <td>issue/blocked</td>
+                  <td>Issue is blocked</td>
+                  <td>#eeeeee</td>
+                </tr>
+                <tr>
+                  <td>issue/design required</td>
+                  <td>Design specification needed</td>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:234]:
```suggestion
                  <td>A labeler bot comments with a note stipulating the a design specification required prior to proceeding.</td>
```

File: src/sections/Community/Handbook/github-process.js [hunk 5]
```diff
@@ -0,0 +1,463 @@
...
+                  <td>#7057ff</td>
+                </tr>
+                <tr>
+                  <td>help wanted</td>
+                  <td>Extra attention is needed</td>
+                  <td>#35f48e</td>
+                </tr>
+                <tr>
+                  <td>issue/invite</td>
+                  <td>Send an invitation to the issue author to join the GH org</td>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:224]:
```suggestion
                  <td>When applied, this label triggers a to send an invitation to the issue author to join the respective GH org. Invitations are missing appropriate team assignments, however.</td>
```

File: src/sections/Community/Handbook/github-process.js [hunk 6]
```diff
@@ -0,0 +1,463 @@
...
+                  <td>#eeeeee</td>
+                </tr>
+                <tr>
+                  <td>issue/invalid</td>
+                  <td>This doesn't seem right</td>
+                  <td>#eeeeee</td>
+                </tr>
+                <tr>
+                  <td>issue/stale</td>
+                  <td>Issue has not had any activity for an extended period of time</td>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:249]:
```suggestion
                  <td>Issue has not had any activity for an extended period of time. Label is most often applied by a stale bot, working under specific inactivity timeouts.</td>
```

File: src/sections/Community/Handbook/github-process.js [hunk 7]
```diff
@@ -0,0 +1,463 @@
...
+                  <td>#eeeeee</td>
+                </tr>
+                <tr>
+                  <td>issue/tweet</td>
+                  <td>Posts</td>
+                  <td>#eeeeee</td>
+                </tr>
+                <tr>
+                  <td>issue/remind</td>
+                  <td>Reminds the contributor towards the issue to be attentive</td>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:259]:
```suggestion
                  <td>A labeler bot comments on the issue with a helpful reminder to the current assignee that help is available, if needed, and a reminder that their issue remains outstanding (undone).</td>
```

File: src/sections/Community/Handbook/github-process.js [hunk 8]
```diff
@@ -0,0 +1,463 @@
...
+                  <td>#eeeeee</td>
+                </tr>
+                <tr>
+                  <td>issue/willfix</td>
+                  <td>This issue will be worked on</td>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:264]:
```suggestion
                  <td>This issue will be worked on. The stale bot honors this label and skips staleness consideration of issues with this label.</td>
```

File: src/sections/Community/Handbook/github-process.js [hunk 9]
```diff
@@ -0,0 +1,463 @@
...
+                  <td>#eeeeee</td>
+                </tr>
+                <tr>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:267]: Is there a forthcoming `issue/valid`, too?

File: src/sections/Community/Handbook/github-process.js [hunk 10]
```diff
@@ -0,0 +1,463 @@
...
+                  <td>service-mesh/nsm</td>
+                  <td>Issues related to NSM</td>
+                  <td>#57b6cc</td>
+                </tr>
+                <tr>
+                  <td>service-mesh/octarine</td>
+                  <td>Issues related to Octarine</td>
+                  <td>#57b6cc</td>
+                </tr>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:406]:
```suggestion
```

Adapter has been archived (and issue label needs to be).

File: src/sections/Community/Handbook/github-process.js [hunk 11]
```diff
@@ -0,0 +1,463 @@
...
+                <tr>
+                  <td>service-mesh/tanzu</td>
+                  <td>Issues related to Tanzu</td>
+                  <td>#57b6cc</td>
+                </tr>
+              </tbody>
+            </table>
+
+            <h3>List for Pull Requests</h3>
+            <p>The following list of pull request labels will be used to both indicate purpose or status of the PR to maintainers, <br/> and significantly, they will be used in conditional logic during workflow execution to determine the PR’s appropriate path through the CI flow.</p>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:416]:
```suggestion
            <p>The following list of pull request labels will be used to both indicate purpose or status of the PR to maintainers, and significantly, they will be used in conditional logic during workflow execution to determine the PR’s appropriate path through the CI flow.</p>
```

File: src/sections/Community/Handbook/github-process.js [hunk 12]
```diff
@@ -0,0 +1,463 @@
...
+            <ul>
+              <li><b>Refactor</b> - Chore related pull request</li>
+              <li><b>Fix</b> - Bug fixes PRs</li>
+              <li><b>On-hold </b> - PR needs review before merging or it needs to behold until a specific issue is fixed.</li>
```
Comment (leecalcote) [inline src/sections/Community/Handbook/github-process.js:420]:
```suggestion
              <li><b>On-hold</b> - PR needs review before merging or it needs to behold until a specific issue is fixed.</li>
```

**Review by leecalcote — APPROVED** [review]

**Comment by sandramsc** [comment]
Thanks for the feedback and content adjustment @leecalcote , I will push the revised content shortly. 👏🏽

**Comment by l5io** [comment]
🚀 Preview for commit c7044790ac997a6df92e98fc186d61637b4aabd0 at: https://6538511e74b30b20b583e5e0--layer5.netlify.app

File: src/components/handbook-navigation/content.js (hunk 1 above)
Comment (sandramsc) [reply src/components/handbook-navigation/content.js:16]: This line here looks exactly like this in my local changes, I've attached a screenshot, perhaps I'm missing something?
screeeeen

File: src/sections/Community/Handbook/github-process.js (hunk 9 above)
Comment (sandramsc) [reply src/sections/Community/Handbook/github-process.js:267]: This might be of value if we chose to lock an issue during triage, or for a somewhat similar process, otherwise, if it's issue/invalid it's "closed". if it's issue/valid it's assigned (the use of the label in question might be slightly redundant otherwise?)

**Comment by l5io** [comment]
🚀 Preview for commit 539bd77fc8763786158df98788eb815818275ce2 at: https://65385d117cc8d91a2ef6f0cd--layer5.netlify.app

**Comment by abhijeetgauravm** [comment]
Hey @sandramsc  Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by sudhanshutech** [comment]
what is the update here @sandramsc

**Comment by sandramsc** [comment]
> what is the update here @sandramsc

Hi @sudhanshutech please have a look at the comment and commit history, if you have feedback it'll be appreciated.

**Comment by abhijeetgauravm** [comment]
Hey @sandramsc Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

File: src/components/handbook-navigation/content.js (hunk 1 above)
Comment (leecalcote) [reply src/components/handbook-navigation/content.js:16]: Oh, your changes are good to go. 👍 

My remark is something of an aside in terms of easing the cost of maintenance in which the section headings and the buildout of the intra-page TOC would be dynamic, not statically written. This is a potential enhancement to separately consider.

**Review by leecalcote — APPROVED** [review]
Rock 'n roll, @sandramsc 👏 👩‍🎤
