### PR TITLE
fixed input text code section

### LINKED ISSUE #6331: Fix Text Input Code Section & Enable Scrolling in Component Sidebar
### Description

While using the UI, I observed two issues that need to be addressed:

The Text Input code section is incomplete and requires further implementation to function correctly.
The Component sidebar lacks a scrolling feature, making it difficult to navigate when there are multiple items. A maximum height should be set to improve usability, and scrolling should be enabled.

### Expected Behavior

- The Text Input code section should be fully completed.
- The sidebar should have a max-height and allow vertical scrolling when needed.

### Screenshots

https://github.com/user-attachments/assets/49f5d2a2-330a-4c5c-bb36-8d591037e82a

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ARYANSHAH1567**
**Description**

This PR fixes #6331 

**Notes for Reviewers**

I have Added a max-width for the sidebar and allowng a vertical scrolling feature, Also the text-input's code section which earlier showed "Sorry this page is still under work" has been replaced with the neccessary code

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 65cec2d81bda472146f7e0671b7c4d3d925e2ddb at: https://687130b9d1c0f917a74ae999--layer5.netlify.app

**Comment by vr-varad** [comment]
I guess there are 2 part of issue and i don't know which one u have resolved. @ARYANSHAH1567

**Comment by ARYANSHAH1567** [comment]
> I guess there are 2 part of issue and i don't know which one u have resolved. @ARYANSHAH1567

My bad, i didnt intercept the issue correctly, will fix one of the two issues and update the pr, Can u please tell me what text has to be added in the Code section of text-input because its currently showing "Sorry this page is still under work"

**Comment by vr-varad** [comment]
U have answered ur own question. @ARYANSHAH1567

**Review by Ayushmore1214 — COMMENTED** [review]
For the code block you can refer this : https://github.com/layer5io/layer5/pull/6541 @ARYANSHAH1567

**Comment by vr-varad** [comment]
@ARYANSHAH1567 
Thank you for your contribution!
Let's discuss this during the website call today at 5:30 PM IST | 7 AM CT

Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

**Comment by l5io** [comment]
🚀 Preview for commit f1a001b7574ed38589f399c9988b944dc285c665 at: https://6874baf313bcbdd9d6eba3a1--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit b35acbec0db8aba42f6cfc049f9e292fb3d99d17 at: https://6874df2a0f821a9ba62aff3a--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 43991dd787ea5d373529be2f5da98114a9f1d23e at: https://68754d5d51c69f8cf1d1b599--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit c4cd765d64aab10d5e4219a8d1e9ae7352e2f5d2 at: https://6875530b51c69fa143d1b27e--layer5.netlify.app

**Comment by ARYANSHAH1567** [comment]
@vr-varad @leecalcote Can u review the PR? i have completed the code section for text input, u can see it at 
[https://6875530b51c69fa143d1b27e--layer5.netlify.app/projects/sistent/components/text-input/code](url)

**Comment by vr-varad** [comment]
@ARYANSHAH1567 follow this pr https://github.com/layer5io/layer5/pull/6605

**Comment by ARYANSHAH1567** [comment]
> @ARYANSHAH1567 follow this pr #6605

Hey @vr-varad,
I've aligned the code.js structure with the  PR example you referenced. The file maintains the showcase format with CodeBlock components for each variant. If there are specific aspects that need further adjustment, please let me know which sections to focus on. Can u review it once

**Comment by LibenHailu** [comment]
LGTM

File: src/sections/Projects/Sistent/components/text-input/code.js [hunk 1]
```diff
@@ -56,10 +75,120 @@ const TextInputCode = () => {
             title="Code"
           />
         </div>
-        <div className="main-content">Sorry, this page is still under work</div>
+        <div className="main-content">
+          <p>
+            Text inputs are important elements that help users interact with an
```
Comment (vr-varad) [inline src/sections/Projects/Sistent/components/text-input/code.js]: mind removing the text that is already present in overview @ARYANSHAH1567

File: src/sections/Projects/Sistent/components/text-input/code.js [hunk 2]
```diff
@@ -56,10 +75,120 @@ const TextInputCode = () => {
...
+            experience by providing text commands that will in turn return
```
Comment (vr-varad) [inline src/sections/Projects/Sistent/components/text-input/code.js]: image
Both seem to be same.

**Comment by l5io** [comment]
🚀 Preview for commit c8f91978d86fffd81e1ca729ea257acf38d605b8 at: https://6883c133f7d4b69697968ced--layer5.netlify.app

**Comment by ARYANSHAH1567** [comment]
> 1. There is still repetitive text in both overview and code.
> 2. There is no parameter as size in `Input`. [ref](https://mui.com/material-ui/api/input/) that is why there is no difference in all 3 input boxes.
>    @ARYANSHAH1567 mind changing it in all 3 sections?

Yeah okay, i will look to complete it and fix it in all three sections

**Comment by vr-varad** [comment]
Thank you for your contribution!
Let's discuss this during the website call today at 5:30 PM IST | 7 AM CT

Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

**Comment by l5io** [comment]
🚀 Preview for commit 12b54e90eb30b8adef41c3acc3a55e16ff80b032 at: https://68870cb7381546d1b73e38c0--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e2acba5130e2704544b54fc5d11694e7368cec2c at: https://688ef241a869ce561223c5a7--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7cf85886c3a08d1d2178779d309fb2bda60fe30a at: https://688f04209921b284b79fb5f4--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7c742071a235a85c8d36f57df2dca5fb8d7bcbf8 at: https://6896f6d8245eab21f86476b9--layer5.netlify.app

**Review by vr-varad — COMMENTED** [review]
image

Please use theme btns @ARYANSHAH1567

**Comment by l5io** [comment]
🚀 Preview for commit e6b8041b86d10598e75ecb682a81505ae36d3553 at: https://6899192c3f756d24ae714025--layer5.netlify.app

**Comment by ARYANSHAH1567** [comment]
@vr-varad 
Does this look fine?
image

**Comment by vr-varad** [comment]
yes @ARYANSHAH1567

**Comment by l5io** [comment]
🚀 Preview for commit 3b3fc8bf3e4f16a4e238af2d429077fa80c9eeb3 at: https://6899b044613dbf09d61defea--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7e1b146a2b7f475063995730ac4d8f42c9089eb2 at: https://6899e98d50d587d4d2e14780--layer5.netlify.app

**Comment by ARYANSHAH1567** [comment]
@FaheemOnHub @vr-varad I have incorporated the changes suggested in meeting, changed it to "Component Props"
Can you please review the PR?

**Comment by l5io** [comment]
🚀 Preview for commit 8a0d698971cb149eaeef961b21d8b86340e394d3 at: https://689b6498721ab745ea48ba95--layer5.netlify.app
