### PR TITLE
Fix dropdown filter bug and minor icon related changes

### LINKED ISSUE #3619: Dropdown filter in Members page is broken.
#### Description

The dropdown menu on the members page is not working as expected. It is not showing the filtered result.

#### Page Link:

https://layer5.io/community/members

#### Expected Behavior

The filter should work properly.

#### Screenshots

Screenshot from 2023-01-13 21-12-46

#### Environment:
- Host OS: Ubuntu 22.04
- Browser: Google Chrome

---
<h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by chinu-anand**
Signed-off-by: Chinu Anand <chinuanand81@gmail.com>

**Description**

This PR fixes #3619 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Well, in this PR you could add the other change to show the badge on the individual member page.

**Comment by Nikhil-Ladha** [comment]
And, we still need to fix the mapping of the label to the Dropdown component in the initial state. So, add that as well.

**Comment by l5io** [comment]
🚀 Preview for commit 640df429c39df75fdd68fae2cee92f00f0929bfc at: https://63c1803da132771b5592eee5--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit ca3a0a6d0357ed888041b2c36f5ced4ed0a632b3 at: https://63c42c436b470a7c9d739c28--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f59bb74facf497a488498791b1df0b7ef2debf9d at: https://63c43f9f0b3413056bf291da--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0a711bcd4d153ad9fecb33d2ea98a0373b802e4c at: https://63c4f1504ce92303949d1096--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit eb60b90f8f94de3ff5e3d0f563a463b7770ed089 at: https://63c4fe0d3a6445082ae15c00--layer5.netlify.app

File: src/pages/community/members.js [hunk 1]
```diff
@@ -201,14 +201,27 @@ const options = [
...
 };
 
+const allMembers = {
+  label: "All Members",
+  value: "all",
+  color: theme.linkColor,
+  isFixed: true,
+  icon: null,
+  className: "allOptions",
+};
```
Comment (Nikhil-Ladha) [inline src/pages/community/members.js:223]: Why do we need this?

Comment (chinu-anand) [reply src/pages/community/members.js:223]: 👀 the current version of the filter when selected shows all members either active or inactive, but previously when the writer badge was not integrated it was only showing the active member. So I was testing with some logic used earlier if that can help in solving the issue. 

I mistakenly added this variable to the commit. If in today's meeting it is decided to show only active members then this part will be needed otherwise I will remove it.

File: src/pages/community/members.js [hunk 2]
```diff
@@ -201,14 +201,27 @@ const options = [
...
+
 const MembersPage = () => {
   /**
    * state storing the currently selected categories.
```
Comment (Nikhil-Ladha) [inline src/pages/community/members.js:227]: At line: 246, pass a new prop named `defaultOption={activeMember}`, and use that prop in the `Dropdown` component for the `defaultValue` prop.

File: src/sections/Community/Members-grid/Dropdown.js [hunk 3]
```diff
@@ -27,7 +27,7 @@ const Dropdown = (props) => {
         >
           <Select
             name="Filter Members"
-            defaultValue={[props.options[11]]}
+            defaultValue={[props.allMembers]}
```
Comment (Nikhil-Ladha) [inline src/sections/Community/Members-grid/Dropdown.js:30]: Update it to `props.defaultOption` as per the above comment.

File: src/pages/community/members.js (hunk 1 above)
Comment (Nikhil-Ladha) [reply src/pages/community/members.js:223]: No need to wait till the meeting.
Remove the `allMember` object, the default value should be `activeMember`

**Comment by l5io** [comment]
🚀 Preview for commit 25f6badad4ce22a0517327a69e07f7470069eadf at: https://63c51e091f9e712f8d2ed138--layer5.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good.
Thank you @chinu-anand :)
