### PR TITLE
Fixed the installation guide

### LINKED ISSUE #2048: [Website][Getting started with Meshery] Correct the installation instruction and Delete One HOMEBREW section
**Description**

Installation instruction in the getting started page (https://layer5.io/service-mesh-management/meshery/getting-started) for some of the plat form are wrong. And also there are two Section which talk about Homebrew (one is under apple logo and another under homebrew logo)
Please correct it .

For Example
```Helm Section should have :
kubectl create namespace meshery
helm install meshery meshery/meshery --namespace meshery
```

**Expected Behavior**

- The correct command should be updated in the below Platform:
Docker, AWS, GKE, KIND, K8s, Linux, Minikube , AKS
- Please delete one of the HomeBrew section as it is listed twice

**Screenshots**

Secreenshot of the section need updation:

Screenshot 2021-07-30 at 9 54 47 PM

---

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by debjani1413**
Signed-off-by: debjani1413 <deydebjani916@gmail.com>

**Description**
The correct command has been updated in the below Platform:
Docker, GKE, KIND, K8s, helm
Deleted the HomeBrew section as it is listed twice
This PR fixes #2048 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by debjani1413** [comment]
@samirparhi-dev please have a look at the PR, I tried my best for updating the installation commands, but I'm not quite sure of some, please suggest the changes!

**Comment by l5io** [comment]
🚀 Preview for commit 56358836c080e487e8bf4a19b5b8198b5d4031d4 at: https://6105812642afb754dea25198--layer5ng.netlify.app

**Comment by Nikhil-Ladha** [comment]
Hey @debjani1413 while you are there and if you are comfortable, can you please fix the the scrolling of the `code` section of the page when a platform is selected in mobile view? The `code` section should be scrollable like the one on the top of the same page.

**Comment by debjani1413** [comment]
@Nikhil-Ladha, you mean about the horizontal scroll that the top `code` part has??

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha, you mean about the horizontal scroll that the top `code` part has??

Yeah, we should be having a similar horizontal scroll for the `code` section for each platform.

**Comment by debjani1413** [comment]
@Nikhil-Ladha okay sure, I'll take it up!

**Comment by samirparhi-dev** [comment]
@debjani1413 : There are few more things needs to be updated. I will catch-up on slack.

**Comment by debjani1413** [comment]
@samirparhi-dev okay sure!!

File: src/sections/Meshery/Meshery-platforms/index.js [hunk 1]
```diff
@@ -39,7 +39,9 @@ const supported_platforms = [
     steps: (
       <>
         <h2>Docker User</h2>
-        <Code codeString={dedent`mesheryctl system start`}
+        <Code codeString={dedent`curl -L https://git.io/meshery | PLATFORM=docker bash - 
+        mesheryctl system start`
```
Comment (leecalcote) [inline src/sections/Meshery/Meshery-platforms/index.js:43]:
```suggestion
`
```

This second command is redundant.

File: src/sections/Meshery/Meshery-platforms/index.js [hunk 2]
```diff
@@ -162,7 +153,7 @@ const supported_platforms = [
     name: "WSL2",
     steps: (
       <>
-        <h2>Winddows User</h2>
+        <h2>Windows User</h2>
         <p>
           Download and unzip mesheryctl from the <a href="https://github.com/layer5io/meshery/releases/">Meshery releases page</a>. Add mesheryctl to your PATH for ease of use. Then, execute:</p>
         <Code codeString={dedent`./mesheryctl system start`}
```
Comment (leecalcote) [inline src/sections/Meshery/Meshery-platforms/index.js:159]:
```suggestion
        <Code codeString={dedent`mesheryctl system start`}
```

**Comment by leecalcote** [comment]
While the homebrew entry is redundant of the Apple entry, let's keep it in the list as there is redundancy across most of the instructions. The goal here is about user choice and presenting them with all options.

**Comment by samirparhi-dev** [comment]
Sure @leecalcote 👍🏼

**Comment by afzal442** [comment]
Nice! Just one suggestion as discussed in the issues to remove one of the HomeBrew sections. I would say we need to delete the `apple` logo instead of ` homebrew` so as to align with the above section of the installation's step as shown below. If that is not we can follow along with Lee as he mentioned above. Thanks.

image

File: src/sections/Meshery/Meshery-platforms/index.js [hunk 3]
```diff
@@ -75,36 +78,22 @@ const supported_platforms = [
...
+        helm install my-meshery meshery/meshery --version 2.1.2`
+        } />
       </>
     )
   },
+  
   {
     icon: Kind,
-    name: "Kind",
+    name: "KinD",
```
Comment (adithyaakrishna) [inline src/sections/Meshery/Meshery-platforms/index.js:90]: @debjani1413 Isn't this supposed to be Kind or kind itself?  I was referring to this, https://kind.sigs.k8s.io/

**Review by adithyaakrishna — CHANGES_REQUESTED** [review]

File: src/sections/Meshery/Meshery-platforms/index.js (hunk 3 above)
Comment (debjani1413) [reply src/sections/Meshery/Meshery-platforms/index.js:90]: Okay sure, sorry for the mistake!

Comment (adithyaakrishna) [reply src/sections/Meshery/Meshery-platforms/index.js:90]: No Probs, Lmk once you have pushed the changes, will re-review it once more :)

**Comment by l5io** [comment]
🚀 Preview for commit a27bd93a476007e5fba783550a24535920e60ec4 at: https://610ad5b993ac8800d5ea2d93--layer5ng.netlify.app

**Review by adithyaakrishna — APPROVED** [review]

**Comment by adithyaakrishna** [comment]
@samirparhi-dev Could you please review this? Thanks :)

**Comment by samirparhi-dev** [comment]
@debjani1413 : Under linux section, please change the command to 

`curl -L https://git.io/meshery | PLATFORM=kubernetes bash -`

**Comment by l5io** [comment]
🚀 Preview for commit 60fc2635c240592aced6159662949f050f4419aa at: https://610aec59a2c4a616e7d7224a--layer5ng.netlify.app

**Comment by samirparhi-dev** [comment]
@debjani1413 : Sorry to trouble you again, the last bit 

Under Azure Kubernetes service user please modify this . All others LGTM

```
mesheryctl system config aks
mesheryctl system start
```
Thanks !

**Review by samirparhi-dev — APPROVED** [review]
LGTM !

**Review by samirparhi-dev — APPROVED** [review]
LGTM

**Comment by l5io** [comment]
🚀 Preview for commit 857c8ce735936221a7e3f592bd82b3d376c388c5 at: https://610af2e2827f0d00ae9282fb--layer5ng.netlify.app

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha @leecalcote Could anyone please merge this? I don't have merge permission for this repo 👀

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Few UI changes:
- Make the width of the code block div: 85% and center align.
- The commands under `Google Kubernetes Engine User` is not properly aligned, please fix that.

**Comment by debjani1413** [comment]
The Helm chart installation steps doesn't quite show up should I fix that too?? @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
> The Helm chart installation steps doesn't quite show up should I fix that too?? @Nikhil-Ladha

Which one? I could see all the commands being listed properly 🤔

**Comment by debjani1413** [comment]
helm
This is what it shows to me... even after my commit it doesn't show up well should I fix it?? @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
I think you are seeing an old preview. Because, as per your [changes](https://github.com/layer5io/layer5/pull/2050/files#diff-752016f1169a259a2301f16c86110c666a8ccddd6a7f2095def7cca15aa2d225R78-R82) the command for `helm` has changed.

**Comment by l5io** [comment]
🚀 Preview for commit bebe6ecd80b720a4a27df0257012af7300cd89c4 at: https://610c270864ac9f00ab4d7704--layer5ng.netlify.app

**Comment by debjani1413** [comment]
oh okay, I've done the required changes, please take a look at it @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Ok, I hate to keep doing this but either make the heading of the `Platform` align with the code section or make the code block 100% width. You can do either of them, whichever is easier.

**Comment by l5io** [comment]
🚀 Preview for commit 0471e2dccc3855e6256ec1cb1f22412bef6d9858 at: https://610d0341b5d12c8eb15f5c87--layer5ng.netlify.app

**Comment by debjani1413** [comment]
@Nikhil-Ladha Ig this looks a lot better, what say??

File: src/components/CodeBlock/index.js [hunk 4]
```diff
@@ -27,7 +29,7 @@ export const LineNo = styled.span`
 
 const CopyCode = styled.button`
   position: absolute;
-  right: 0;
+  right: 5em;
```
Comment (Nikhil-Ladha) [inline src/components/CodeBlock/index.js:32]: This will affect all the places where this component is used, have you confirmed if it is looking fine in all the other places and in all views?

File: src/sections/Meshery/Meshery-platforms/index.js [hunk 5]
```diff
@@ -24,7 +24,7 @@ const supported_platforms = [
     name: "Apple",
     steps: (
       <>
-        <h3>macOS User</h3>
+        <h3>MacOS User</h3>
```
Comment (Nikhil-Ladha) [inline src/sections/Meshery/Meshery-platforms/index.js:27]: This should be `h2` like the ones below.

Comment (Nikhil-Ladha) [reply src/sections/Meshery/Meshery-platforms/index.js:27]: Same goes for `Brew user` as well

**Comment by l5io** [comment]
🚀 Preview for commit 35522891762943ae8cab543d240745d3fd84f60b at: https://610d4c30b5d12cd1e95f5da2--layer5ng.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]
