### PR TITLE
[Products] Resolve slider carousel image invisibility in production build

### LINKED ISSUE #7461: The slide transitions on the Meshery pages are not working.
### Description
https://layer5.io/cloud-native-management/meshery  On page 

https://github.com/user-attachments/assets/013ce306-155e-42b2-a5d9-011c5b9066b8

### Expected Behavior
Animation should be working.

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Bharath314**
**Description**

This PR fixes #7461.

This bug was caused by react-slick not playing nice with Gatsby's `StaticImage`. It looks like some sort of height miscalculation issue caused by the way Gatsby Image pipeline works in production, which probably explains why the carousel works in dev but not prod. ~I switched to standard `` tags to fix this issue.~

**Edit:** I kept the `StaticImage` components and instead added `height: auto` for the slick components, fixing the issue.

**Notes for Reviewers**
I'm opening a draft PR so that I can get a preview to test my changes because I can't run `make build` on my PC without it crashing from running out of memory.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 95c663bed147191e912476f63c9db9df8926f9aa at: https://69ce5320c9c507488f57205e--layer5.netlify.app

**Comment by Bharath314** [comment]
Looks like that didn't work. I'll have to try something else.

**Comment by leecalcote** [comment]
Is this still a draft PR or is it ready for review, @Bharath314?

**Comment by Bharath314** [comment]
@leecalcote It's still a draft PR. I can tell that it's a height miscalculation issue being caused by either react-slick or gatsby, but I haven't yet figured out why this bug happens only on production and not on a development server. 

I'll mark it ready for review as soon as I am done with the bug. I opened a draft PR because I needed some way to preview how the site looks like on production because I'm unable to run `make build` which crashes my PC. I hope that it is ok?

File: src/sections/Meshery/Features-section/index.js [hunk 1]
```diff
@@ -47,12 +46,16 @@ const FeaturesSection = () => {
...
+            Design it <span>visually and collaboratively</span>
+          </h1>
           {/* <h1>
             <span>Meshery</span> supports the most service meshes.
           </h1> */}
           <p>
-            No matter where you run your workloads, Meshery's Kanvas makes Kubernetes and cloud infrastructure design intuitive and collaborative.
+            No matter where you run your workloads, Meshery's Kanvas makes
+            Kubernetes and cloud infrastructure design intuitive and
+            collaborative.
```
Comment (saurabhraghuvanshii) [inline src/sections/Meshery/Features-section/index.js]: @Bharath314  keep this in one line Please

File: src/sections/Meshery/Features-section/index.js [hunk 2]
```diff
@@ -61,10 +64,12 @@ const FeaturesSection = () => {
             <Col $xs={12} $xl={4} className="smp-section-data">
               <h2>The Visual Designer: Kanvas</h2>
               <p>
-                Drag, drop, and deploy your infrastructure with ease. Kanvas, built on Meshery, simplifies Kubernetes and cloud management through intuitive visual designer and operator.
+                Drag, drop, and deploy your infrastructure with ease. Kanvas,
+                built on Meshery, simplifies Kubernetes and cloud management
+                through intuitive visual designer and operator.
```
Comment (saurabhraghuvanshii) [inline src/sections/Meshery/Features-section/index.js]: @Bharath314  same here 
```suggestion
                Drag, drop, and deploy your infrastructure with ease. Kanvas, built on Meshery, simplifies Kubernetes and cloud management through intuitive visual designer and operator.
```

File: src/sections/Meshery/Features-section/index.js (hunk 1 above)
Comment (saurabhraghuvanshii) [inline src/sections/Meshery/Features-section/index.js]:
```suggestion
            No matter where you run your workloads, Meshery's Kanvas makes Kubernetes and cloud infrastructure design intuitive and collaborative.
```

File: src/sections/Meshery/Features-section/index.js [hunk 3]
```diff
@@ -83,17 +88,35 @@ const FeaturesSection = () => {
           <div>
             <h3>One step to managing your microservices</h3>
             <h1>Cloud Native Application Management</h1>
-            <p>Confidently take full advantage of all that your infrastructure offers.</p>
+            <p>
+              Confidently take full advantage of all that your infrastructure
+              offers.
```
Comment (saurabhraghuvanshii) [inline src/sections/Meshery/Features-section/index.js]:
```suggestion
              Confidently take full advantage of all that your infrastructure offers.
```

**Comment by saurabhraghuvanshii** [comment]
Thanks @Bharath314  lgtm!!
