### PR TITLE
fix: resolve dark mode flicker issue

### LINKED ISSUE #7443: Dark mode flicker — white background appears briefly before theme loads
### Description

When opening the Layer5 website, there is a brief white background flash before the dark theme loads. This creates a noticeable flicker effect and impacts the perceived user experience.

This appears to be a theme initialization or CSS loading timing issue (FOUC — Flash of Unstyled Content).

### Expected Behavior

The website should load directly with the correct theme background (dark mode) without any white flash.

### Screenshots

https://github.com/user-attachments/assets/56190ce6-e9a4-43ea-90e7-4b1f2b3da618

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by AnkitRewar11**
**Description**
This PR fixes #7443 

This PR resolves the dark mode flicker issue. On page load, the theme 
was not being applied before render which caused a visible flicker. 
Updated ThemeManager.js, StyledThemeProvider.js, and onRenderBody.js 
to properly handle theme initialization and prevent flash of unstyled 
content (FOUC).

**Notes for Reviewers**
- Updated ThemeManager.js to handle dark mode state properly
- Updated StyledThemeProvider.js for consistent theme application  
- Updated onRenderBody.js to inject correct theme class before render
- No new dependencies added
- Only 3 files changed

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit a5c4a7d719892bd8fc050f620be860ca9ff51b60 at: https://69bea5593286e0c4d4ee82dc--layer5.netlify.app

**Comment by AnkitRewar11** [comment]
@YASHMAHAKAL Thank you so much for the review and support! 🙏
Really appreciate your guidance throughout this PR. 
Looking forward to getting it merged! 😊

**Comment by l5io** [comment]
🚀 Preview for commit 8d09e77110daadc6185abd6a4801e330b12cc969 at: https://69befa12ca8054dc493243ab--layer5.netlify.app

**Comment by Bhumikagarggg** [comment]
@AnkitRewar11 Want to merge this PR? Add it as an agenda item to the [meeting minutes](https://meet.layer5.io/websites-minutes), if you would 🙂! Thank you for your contribution! Let's discuss this during the website call tomorrow at 5:30 PM IST | 7 AM CST.

File: src/theme/app/StyledThemeProvider.js [hunk 1]
```diff
@@ -1,22 +1,16 @@
-//uses isDark state to choose styled-component theme (in themeStyles.js)
-//and use ThemeProvider to allow all styled components access to values via props.theme
-
```
Comment (leecalcote) [inline src/theme/app/StyledThemeProvider.js:3]: Are these comments inaccurate or unhelpful?

If they are inaccurate because of the changes that you've made, then update what they say.

If they are not helpful, then update what they say.

**Review by leecalcote — CHANGES_REQUESTED** [review]

File: src/theme/app/ThemeManager.js [hunk 2]
```diff
@@ -129,14 +128,10 @@ export const ThemeManagerProvider = (props) => {
...
       }
 
-      // Update state
       setIsDark(newIsDark);
       setThemeSetting(setting);
 
-      // Apply to DOM immediately
       applyThemeToDOM(themeToApply);
-
-      // Persist to localStorage
```
Comment (leecalcote) [inline src/theme/app/ThemeManager.js:139]: Reinstate the comments.

File: onRenderBody.js
Comment (leecalcote) [inline onRenderBody.js:1]: Why was the existing approach completely ripped out and replaced?

What is precisely wrong with the current approach? Fix that.

If the current approach is completely offbase - ok - explain that and why a complete rewrite is needed.

**Review by leecalcote — CHANGES_REQUESTED** [review]

**Comment by leecalcote** [comment]
@AnkitRewar11 without details as to where specifically we're failing in the current implementation, and without details as to how your completely new approach resolves the problem, we're flying blind - - and this doesn't work.

**Comment by l5io** [comment]
🚀 Preview for commit 9ad62cbd0f947c8ea9d8cca59b79d96220ed4be8 at: https://69c0e4f81e80d04a59c24468--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9736016cbf48d9af6558405ece9b1285e5ec8a28 at: https://69c0f0bce6282fe4fa13bfa3--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 42eab577a76e0a3d4abf14c2f8fae223906e1a3c at: https://69c0fbc40e47164cd82d99e2--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f00fabd00b55e02a32e0ed95bbbcaacd5b1fd1b8 at: https://69c10fd10e471689402d9987--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit f60787adcbfcb733a042faa1242d66e276df73b5 at: https://69c117e633aecf2bd975d0d1--layer5.netlify.app

**Comment by AnkitRewar11** [comment]
Hello, you make a fair point. I was wrong to get rid of the original approach and do a full rewrite. That made the diff really hard to look at. It hid the actual fix. That was my mistake.

I went back to the version. I put back the architecture, the modern syntax and all the comments.

This pull request is now a simple fix. After looking into the server side rendering lifecycle I found out why the master branch was not working and what I needed to change to fix it:

1. When the code runs (setPreBodyComponents → setHeadComponents)

The original code put the script in the body of the html. By the time this runs the browser has already started showing the default light styles. I moved it to the head of the html so that it stops the paint until the css variables are calculated and applied.

2. Turning on styles (data-theme)

The old script put in css variables but it did not set the data-theme attribute on the root of the html. Our global css needs this attribute to work. The variables were there but the background color was not changing before hydration. I added a line of code to fix this.

3. Working with React (window.__theme)

The server side rendering was calculating the theme. The ThemeManager did not know about it when the client first loaded. It was using the mode by default, which caused a flicker when the page loaded. I made it so that the ThemeManager can pick up the theme that was calculated by the server side rendering.

4. Fixing the crash that was not showing an error

The master branch was using JSON.parse to parse a string. This is not a way to do it. If any theme string has a quote, in it it breaks and causes a syntax error, which stops the dark mode from working. I changed it so that it passes the string as an object.

The diff should be easier to look at now. The flash of unwanted content is completely gone.

**Comment by YASHMAHAKAL** [comment]
@AnkitRewar11 even this time you've responded to review with 5-6 new commits. and the description you post after your commits, it was even relevant to your first commit, and about diff's looking easy, they were much easy before : )

correct me if i'm wrong, Thanks for your efforts :+1:

**Comment by AnkitRewar11** [comment]
> @AnkitRewar11 even this time you've responded to review with 5-6 new commits. and the description you post after your commits, it was even relevant to your first commit, and about diff's looking easy, they were much easy before : )
> 
> correct me if i'm wrong, Thanks for your efforts :+1: 

You were right my previous approach was also correct. But yesterday Lee suggested a few changes, like adding the comments again, and I’ve done that now.

As for the current approach, there isn’t much difference between the two. I just made minimal changes to the old code so that it’s easier to understand. 

And regarding the new commits, I accidentally made the changes directly here instead of locally, so that’s why so many commits were created. Sorry about that.

File: src/theme/app/ThemeManager.js [hunk 3]
```diff
@@ -36,29 +37,37 @@ const applyThemeToDOM = (theme) => {
...
 
   useEffect(() => {
     if (!isBrowser) return;
 
     const root = window.document.documentElement;
-    const initialColorValue = root.style.getPropertyValue("--initial-color-mode");
+    const initialColorValue = (root.style.getPropertyValue("--initial-color-mode") || "").trim();
+    const actualTheme = window.__theme || initialColorValue || ThemeSetting.LIGHT;
 
-    // Get stored theme from localStorage
```
Comment (rishiraj38) [inline src/theme/app/ThemeManager.js:52]: Please don’t remove the comments.

Comment (AnkitRewar11) [reply src/theme/app/ThemeManager.js:52]: Hi @RishiRaj38, I hope everything got added properly. I’ve added that one comment as you suggested.

**Comment by l5io** [comment]
🚀 Preview for commit 3a170b6111b0e512c26d487f1a02ba048880815d at: https://69cbbf473ddc3f5da4372c0f--layer5.netlify.app

**Comment by rishiraj38** [comment]
@saurabhraghuvanshii, could you please take a look at this PR?

**Comment by l5io** [comment]
🚀 Preview for commit 00e33682dd60e0d18d967914985cb6bac6a8cbe6 at: https://69cc166e700405aa29e3d071--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2dc387ad8c752aa6e256fb78b1288da3456baad5 at: https://69ce48ebf7b0d22bdba1b3a4--layer5.netlify.app

File: onRenderBody.js [hunk 4]
```diff
@@ -5,53 +5,76 @@ import lighttheme, { darktheme } from "./src/theme/app/themeStyles";
 const themes = { light: lighttheme, dark: darktheme };
 
 const MagicScriptTag = (props) => {
+  // FIX: Stringify the theme object outside the template literal to prevent
```
Comment (rishiraj38) [inline onRenderBody.js]: @AnkitRewar11  Please complete the comment here `to prevent `what?

File: src/theme/app/ThemeManager.js [hunk 5]
```diff
@@ -36,19 +37,28 @@ const applyThemeToDOM = (theme) => {
...
+  });
 
   useEffect(() => {
     if (!isBrowser) return;
 
     const root = window.document.documentElement;
-    const initialColorValue = root.style.getPropertyValue("--initial-color-mode");
-
+    const initialColorValue = (root.style.getPropertyValue("--initial-color-mode") || "").trim();
+    const actualTheme = window.__theme || initialColorValue || ThemeSetting.LIGHT;
```
Comment (rishiraj38) [inline src/theme/app/ThemeManager.js]: Fallback to DARK (consistent with onRenderBody.js)  

```suggestion
    const actualTheme = window.__theme || initialColorValue || ThemeSetting.DARK;
```

**Comment by l5io** [comment]
🚀 Preview for commit bc5a6da1a9b2aaf0bff64755c893b5e1128025ad at: https://69cf8b5fc52dd1b6e3c3ee10--layer5.netlify.app

File: src/theme/app/ThemeManager.js (hunk 5 above)
Comment (AnkitRewar11) [reply src/theme/app/ThemeManager.js]: Good catch @rishiraj38! I’ve fixed the incomplete sentence, updated the comment for clarity, and tested everything locally no FOUC/flicker. Pushed the update 👍

File: onRenderBody.js
Comment (saurabhraghuvanshii) [reply onRenderBody.js:1]: @AnkitRewar11  can you answer this?

Comment (AnkitRewar11) [reply onRenderBody.js:1]: Hey @saurabhraghuvanshii, just wanted to clearly explain why the master branch approach was failing and how this PR fixes it.

I’ve only made a few focused fixes to solve the dark mode flicker issue:

Wrong Injection Placement: The script was running too late (inside <body>), so the page first showed light mode. I moved it to <head> so the correct theme loads before anything is displayed.

Missing data-theme: The code wasn’t setting the data-theme attribute on the HTML root, which is needed for dark mode styles. I’ve added that.

SSR / Hydration Mismatch: The server knew the theme, but the frontend didn’t, so it defaulted to light mode and caused flicker. I fixed this by passing the theme (window.__theme) so both stay in sync.

JSON Parsing Issue: The previous way of parsing theme data could break if there were quotes in the string. I made it safer to avoid crashes.

Now the changes are minimal, clean, and focused and the flicker issue is completely resolved. I hope all your questions have been answered. If there’s anything else you’d like to know, please let me know.

File: src/theme/app/StyledThemeProvider.js [hunk 6]
```diff
@@ -16,7 +16,7 @@ export const StyledThemeProvider = (props) => {
   // This ensures the server and client render the same thing initially
   const currentTheme = isDark ? darkTheme : lightTheme;
   const theme = {
-    ...(didLoad || !isBrowser ? currentTheme : transformTheme(currentTheme)),
+    ...(didLoad ? currentTheme : transformTheme(currentTheme)),
```
Comment (YASHMAHAKAL) [inline src/theme/app/StyledThemeProvider.js:16]: @AnkitRewar11 since !isBrowser is removed here, we have a unused declared function in same file at top, it'll be nice to remove it then.

File: onRenderBody.js [hunk 7]
```diff
@@ -5,53 +5,76 @@ import lighttheme, { darktheme } from "./src/theme/app/themeStyles";
...
   return <script dangerouslySetInnerHTML={{ __html: codeToRunOnClient }} />;
 };
 
-export const onRenderBody = ( { setPreBodyComponents }) => {
-  setPreBodyComponents(<MagicScriptTag key="theme-injection" theme={themes} />);
-};
+// FIX: Using setHeadComponents instead of setPreBodyComponents ensures the script runs
+// strictly in the <head>, blocking the first paint until the theme is applied and completely eliminating FOUC.
+export const onRenderBody = ( { setHeadComponents }) => {
+  setHeadComponents([<MagicScriptTag key="theme-injection" theme={themes} />]);
```
Comment (YASHMAHAKAL) [inline onRenderBody.js:79]: @AnkitRewar11 now that you've built out this robust theme calculation logic here in the <head>, I suspect there is still an older, half-finished script hanging around in html.js, see if it's serving for any other cause if not worth removing that ? just cleanup needed, LGTM otherwise !

**Comment by YASHMAHAKAL** [comment]
@AnkitRewar11 I'll encourage you to add this PR as an agenda item to the [meeting minutes](https://meet.layer5.io/websites-minutes), if you would 🙂! Thank you for your contribution! Let's discuss this during the website call tomorrow at 5:30 PM IST | 7 AM CST.

File: src/theme/app/StyledThemeProvider.js (hunk 6 above)
Comment (AnkitRewar11) [reply src/theme/app/StyledThemeProvider.js:16]: removed 👍

File: onRenderBody.js (hunk 7 above)
Comment (AnkitRewar11) [reply onRenderBody.js:79]: @YASHMAHAKAL Thanks, I’ve made this change as well. There was some theme-related code in **html.js** which I’ve removed since it’s no longer needed. The rest of the code is the same.

**Comment by arjunmehta-git** [comment]
This has come a long way, @AnkitRewar11, and your detailed explanation of the four root causes (script placement in `setPreBodyComponents` vs `setHeadComponents`, missing `data-theme` attribute, `window.__theme` SSR handoff, and the `JSON.parse` crash risk) is exactly the kind of analysis that helps reviewers understand and trust the fix.

Since this has approvals from both @YASHMAHAKAL and @rishiraj38 on the current commit, and the core FOUC mechanism is well-explained, I'd like to see one final thing before this merges:

- **Manual FOUC verification** — Please test by hard-refreshing the Netlify preview in both light and dark mode (with the mode stored in `localStorage`) and confirm there is no visible flash. A short screen recording or a "tested, no flicker observed" comment from a reviewer who verified the Netlify preview would close this out.

One process note for future PRs: responding to review feedback by pushing many small fixup commits makes the diff harder to follow. Consider squashing fixup commits locally (`git rebase -i`) before pushing so the history stays readable. It also makes it easier for reviewers to see the net effect of your changes.

Good work seeing this through.

**Comment by AnkitRewar11** [comment]
> This has come a long way, @AnkitRewar11, and your detailed explanation of the four root causes (script placement in `setPreBodyComponents` vs `setHeadComponents`, missing `data-theme` attribute, `window.__theme` SSR handoff, and the `JSON.parse` crash risk) is exactly the kind of analysis that helps reviewers understand and trust the fix.
> 
> Since this has approvals from both @YASHMAHAKAL and @rishiraj38 on the current commit, and the core FOUC mechanism is well-explained, I'd like to see one final thing before this merges:
> 
> - **Manual FOUC verification** — Please test by hard-refreshing the Netlify preview in both light and dark mode (with the mode stored in `localStorage`) and confirm there is no visible flash. A short screen recording or a "tested, no flicker observed" comment from a reviewer who verified the Netlify preview would close this out.
> 
> One process note for future PRs: responding to review feedback by pushing many small fixup commits makes the diff harder to follow. Consider squashing fixup commits locally (`git rebase -i`) before pushing so the history stays readable. It also makes it easier for reviewers to see the net effect of your changes.
> 
> Good work seeing this through.

Thanks for the detailed review and guidance, @arjunmehta-git.

Currently, we are not using Netlify. I am waiting for the GitHub Actions Pages setup to be completed so I can provide final verification proof (screen recording or confirmation).

The FOUC-related changes have been tested locally, and no visible flash was observed. I will share final verification once the setup is ready.

Please let me know if anything else should be validated before merge. Appreciate the feedback and support. 🫡🙏
