### PR TITLE
[Individual-Integrations] Fix logo scaling and make the integrations page responsive

### LINKED ISSUE #6578: responsive bug on integrations pages
### Description

Visit any https://layer5.io/cloud-native-management/meshery/integrations individual page:
notice the hero section

### Expected Behavior

- Let's identify what caused this
- fix it
### Screenshots

Image
### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ShirshenduR**
**Description**

This PR fixes #6578 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 64995377e025dabb6f72ab939a8cc504b93c1c05 at: https://6860503b8482fc81713147c5--layer5.netlify.app

**Comment by vishalvivekm** [comment]
Thank you for working on this @ShirshenduR.
- Did you find out what caused this?

**Comment by l5io** [comment]
🚀 Preview for commit 227e222404b01b5561f1a149062ba11ad85f3de3 at: https://68616b7e4215d215ccea656b--layer5.netlify.app

**Comment by ShirshenduR** [comment]
@vishalvivekm The root cause for the issue is in the Image component `image.js` as The img tag has inline styles: [aspectRatio: "16/9"] which is forcing a 16:9 ratio on all logos

**Comment by l5io** [comment]
🚀 Preview for commit a36f095cfb429345f515d4dd01a78c44306435a0 at: https://68617c1d066d25d632bf1c73--layer5.netlify.app

**Review by vishalvivekm — CHANGES_REQUESTED** [review]
@ShirshenduR Please revert extraneous commits / lint changes

**Comment by l5io** [comment]
🚀 Preview for commit 6dabd37598d82cd9b5f24c88956f37442600cc2a at: https://68618f785b00177464aeb5f4--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 55c7688b811773f2d2d317a49436344a04ea8d23 at: https://68622cf297cef8a8143a8ee0--layer5.netlify.app

**Comment by vr-varad** [comment]
@ShirshenduR 
Thank you for your contribution!
Let's discuss this during the website call today at 7 AM CT

Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

**Comment by vishalvivekm** [comment]
> @vishalvivekm The root cause for the issue is in the Image component `image.js` as The img tag has inline styles: [aspectRatio: "16/9"] which is forcing a 16:9 ratio on all logos

@KrishnaShuk

**Comment by ShirshenduR** [comment]
> > @vishalvivekm The root cause for the issue is in the Image component `image.js` as The img tag has inline styles: [aspectRatio: "16/9"] which is forcing a 16:9 ratio on all logos
> 
> @KrishnaShuk

Please review the changes now @vishalvivekm

**Comment by vishalvivekm** [comment]
Let's note that the fixed aspect ratio was added to help improve the CLS(Cumulative Layout Shift) score. However, since it's causing image distortion, we're reverting that. 
The 300+ integration pages rarely experience layout shifts due to these integration icons, as they are small. That said, there may be other places where this might not be the case.

File: src/components/image.js [hunk 1]
```diff
@@ -5,15 +5,14 @@ const Image = ({ childImageSharp, extension, publicURL, alt, imgStyle, ...rest }
...
+      <div className="old-gatsby-image-wrapper" style={{ width: "100%", height: "auto" }}>
         <img
           src={publicURL}
           alt={alt || "Blog image"}
           width="100%"
           height="auto"
           style={{
-            aspectRatio: "16/9",
-            objectFit: imgStyle?.objectFit || "cover",
+            objectFit: imgStyle?.objectFit || "contain",
```
Comment (vishalvivekm) [inline src/components/image.js]: instead of changing the fallback in this global component, let's pass `object-fit: contain` from individual integration page's template.

`Meshery-integrations/Individual-Integrations`

Comment (ShirshenduR) [reply src/components/image.js]: What about the aspect ratio I removed it from here is this ok as it always got added to img and old-gatsby-wrapper making the icons distorted and unusual extra space?

Comment (vishalvivekm) [inline src/components/image.js]:
```suggestion
            objectFit: imgStyle?.objectFit || "cover",
```

**Review by vishalvivekm — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 2e520971665e8a0646a929cce570209f0cb1790d at: https://6862cf76d2a3cd832aa27671--layer5.netlify.app
