### PR TITLE
fix: enable svg thumbnail support in Card and listing queries

### LINKED ISSUE #7387: [BUG] Blog page cards show missing images
### Description
On the Blog page, several blog cards are rendered without their cover images, while others display images correctly.
This results in an inconsistent UI and breaks the visual layout of the blog grid.

From the screenshots, some cards show only the title, date, author, and “see more” link, but the image area is blank.

### Expected Behavior

- All blog cards should consistently display their associated cover images
- If an image is missing from the source, a fallback/placeholder image should be shown to maintain layout consistency

### Screenshots

Image
Image
Image
Image
Image
Image
Image
Image

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/GvB8SudhEOoq3JOvoLaoMs)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by rishiraj38**
**Description**

This PR fixes #7387  resolves an issue where blog posts using SVG thumbnails (e.g., "The Mythical 10x Engineer") were displaying blank cards on the blog listing page.

Screenshot 2026-01-30 at 11 28 07 PM

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by rishiraj38** [comment]
@saurabhraghuvanshii  Please Review .

**Comment by l5io** [comment]
🚀 Preview for commit f0533344650274ba870cb8d62c42ae82b52868ef at: https://697cf4fcb364100077022b23--layer5.netlify.app

**Comment by saurabhraghuvanshii** [comment]
Thanks @rishiraj38  lgtm!!

File: src/pages/blog/index.js [hunk 1]
```diff
@@ -25,13 +25,21 @@ export const query = graphql`query allBlogs {
...
         }
+        thumbnail_svg {
+          extension
+          publicURL
+        }
         darkthumbnail {
           extension
           publicURL
           childImageSharp {
             gatsbyImageData(layout: FULL_WIDTH)
```
Comment (saurabhraghuvanshii) [inline src/pages/blog/index.js:32]: @rishiraj38  don't we need this in https://github.com/layer5io/layer5/pull/7388/files#diff-f3ff5ef15389e9dc360a554de5d6a1d3243d1407e107c8c462c5c01350eb5be3R28

File: src/pages/blog/index.js [hunk 2]
```diff
@@ -25,13 +25,21 @@ export const query = graphql`query allBlogs {
...
           }
         }
+        darkthumbnail_svg {
```
Comment (saurabhraghuvanshii) [inline src/pages/blog/index.js]: same here

File: src/pages/blog/index.js (hunk 1 above)
Comment (rishiraj38) [reply src/pages/blog/index.js:32]: gatsby-plugin-sharp doesn't work on SVGs because they are vectors, not raster images. We just need publicURL to render them directly. Adding childImageSharp would break the query.

**Comment by rishiraj38** [comment]
Is this good or should I convert the SVGs to PNG or WebP and fix the issue?

**Comment by saurabhraghuvanshii** [comment]
It would be better to convert to webp

**Comment by rishiraj38** [comment]
Having made the changes I think we should convert all SVGs to WebP or PNGs to avoid any future errors.

**Comment by rishiraj38** [comment]
I’ll fix that in the next PR.  Please let me know if there’s anything else needs fixing.

**Comment by l5io** [comment]
🚀 Preview for commit 28855b1893a046995216ecc18c6c21b2000851da at: https://697d0718404c6541fc202452--layer5.netlify.app

**Comment by saurabhraghuvanshii** [comment]
@rishiraj38 what about svgs images why didn't you remove them? Is they are missing?

**Comment by rishiraj38** [comment]
> @rishiraj38 what about svgs images why didn't you remove them? Is they are missing?

I kept them because some are still used inside the blog content itself (imported in the MDX). Deleting them would crash the build.

**Comment by l5io** [comment]
🚀 Preview for commit 773b5f8d197d7bcf22363a3a5ffce6de18859e47 at: https://697d0be598129d5678744d5a--layer5.netlify.app

**Comment by saurabhraghuvanshii** [comment]
Thanks @rishiraj38 lgtm!!
