### PR TITLE
Fix placeholder text in Text Input component

### LINKED ISSUE #5738: Rename the PlaceHolder Text
### Description

image
So here in the PlaceHolder the text is `PlaceHolder goes here` instead i think it should be `placeHolder`

You can check this here : https://layer5.io/projects/sistent/components/text-input

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by siddharthbaleja7**
### Description
This PR addresses an issue with the placeholder text in the Text Input component. The current placeholder text reads "PlaceHolder goes here" when it should be "placeHolder". 
Fixes #5738 

### Expected Behavior
The placeholder text should be updated to display "placeHolder" instead of "PlaceHolder goes here". You can review the component at [Sistent Text Input](https://layer5.io/projects/sistent/components/text-input) for reference.

### Changes Made
- Updated the placeholder text from "PlaceHolder goes here" to "placeHolder" in the Text Input component.

Please review the changes and let me know if further adjustments are needed.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 27350030afa62cd6c6f54de6813d396a0f94d83f at: https://66ad2ae995b5979fbce46b75--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit fcdf1acf359a4e033ba330ca9d9601577455fcf5 at: https://66ad342943ec4dab4df6f5e9--layer5.netlify.app

**Comment by siddharthbaleja7** [comment]
@Ashparshp Can you please review this PR.

**Comment by siddharthbaleja7** [comment]
@Ashparshp Can you please review this PR.

**Comment by Ashparshp** [comment]
@siddharthbaleja7 Thanks for your contribution, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

File: src/sections/Projects/Sistent/components/text-input/guidance.js [hunk 1]
```diff
@@ -80,7 +80,7 @@ export const TextInputGuidance = () => {
           </p>
           <Row Hcenter>
             <SistentThemeProvider initialMode={isDark ? "dark" : "light"}>
-              <Input placeholder="Placeholder goes here" />
+              <Input placeholder="PlaceHolder" />
```
Comment (sudhanshutech) [inline src/sections/Projects/Sistent/components/text-input/guidance.js:83]: use 
```suggestion
              <Input placeholder="Placeholder" />
```

**Review by sudhanshutech — CHANGES_REQUESTED** [review]

**Comment by sudhanshutech** [comment]
@siddharthbaleja7 there is a small change requested. Will you able to quickly complete that?

**Comment by siddharthbaleja7** [comment]
@sudhanshutech Sure

**Comment by l5io** [comment]
🚀 Preview for commit 975273ac49ddac7b30e44b3a4a92ec9b08b0c977 at: https://66b45c24be40e59a6a01572d--layer5.netlify.app

**Review by sudhanshutech — APPROVED** [review]
