### PR TITLE
fixed Darkmode-Lightmode switching issue

### LINKED ISSUE #6484: Card Text Labels Become Invisible When Switching Between Dark and Light Themes
### Description

When switching between dark and light themes on the Layer5 website, the text labels under the technology icons (Flux, SPIRE, Harbor, OpenTelemetry, Helm, TiKV, etc.) become invisible due to incorrect text color handling. The text appears to maintain a white color when switching back to dark theme, making it invisible against the dark background.

### Expected Behavior

* Text labels should remain visible and properly contrasted in both dark and light themes
* Text color should dynamically adjust based on the selected theme

### Screenrecord

https://github.com/user-attachments/assets/20f3cc80-5ed8-46bc-8dda-8212f50e14fd

### Environment:
- Host OS: Debian 12
- Browser: Firefox

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ashok-2003**
**Description**

This PR fixes #6484 (Card Text Labels Become Invisible When Switching Between Dark and Light Themes)

**Notes for Reviewers**
- Fixed some indentation issues.  
- Added proper theme colors for the text.

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 9892ceae2e85a84e38dc20f9f7a2e2e7c86d478a at: https://683fac9decdd6d7e89e1a9ba--layer5.netlify.app

**Comment by vr-varad** [comment]
some screen shots or recording will be helpful to review it @ashok-2003

**Comment by ashok-2003** [comment]
sure @vr-varad , 

https://github.com/user-attachments/assets/3c490f0c-6461-4fdd-a194-94f76027592b

**Comment by vr-varad** [comment]
@M-DEV-1

File: src/sections/Home/Playground-home/index.js [hunk 1]
```diff
@@ -215,7 +199,8 @@ const ViewsSectionWrapper = styled.div`
       height:150px;
       padding: 2rem;
       box-sizing: border-box;
-      background-color: ${(props) => props.theme.backgroundColor}; 
+      background-color: ${(props) => props.theme.grey191919ToGreyF2F5F7};
```
Comment (M-DEV-1) [inline src/sections/Home/Playground-home/index.js]: @ashok-2003 we want to refrain from using props or tokens other than the ones mentioned in this [palette](https://github.com/layer5io/sistent/blob/master/src/theme/palette.ts)

File: src/sections/Home/Playground-home/index.js [hunk 2]
```diff
@@ -67,89 +67,73 @@ const ViewsSectionWrapper = styled.div`
...
-    .hero-image {
-        position: relative;
-        display: flex;
-        justify-content: center;
-        flex: 0 0 50%;
-        max-width: 50%;
-        overflow: hidden;
-        height: 100%;
+  .hero-text {
+    display: flex;
```
Comment (M-DEV-1) [inline src/sections/Home/Playground-home/index.js]: @ashok-2003 it would be nice if you keep the indentation fixes in a commit towards the end, that way it's easier to track changes .

File: src/sections/Home/Playground-home/index.js (hunk 1 above)
Comment (M-DEV-1) [reply src/sections/Home/Playground-home/index.js]: Apologies, I just realised that these components are not using [Sistent](https://github.com/layer5io/sistent).

Can you use the `isDark` function? and toggle the colors accordingly? The backgroundColor token works fine, I believe. It's the text which we have to keep track of.

**Comment by LibenHailu** [comment]
If there are formatting issues, It would be nice to address them, as for the backgrounds 
`      background-color: ${(props) => props.theme.backgroundColor}; 
      background-color: ${(props) => props.theme.grey191919ToGreyF2F5F7};
`
I think they are good contrasting colors for our theme, considering our theme stays consistent, LGTM!

**Comment by M-DEV-1** [comment]
> If there are formatting issues, It would be nice to address them, as for the backgrounds 
> `      background-color: ${(props) => props.theme.backgroundColor}; 
>       background-color: ${(props) => props.theme.grey191919ToGreyF2F5F7};
> `
> I think they are good contrasting colors for our theme, considering our theme stays consistent, LGTM!

@LibenHailu yes, I don't think that `props.theme.grey191919ToGreyF2F5F7` is a default theme that we're using in our site

**Comment by LibenHailu** [comment]
> > If there are formatting issues, It would be nice to address them, as for the backgrounds
> > `     background-color: ${(props) => props.theme.backgroundColor};  background-color: ${(props) => props.theme.grey191919ToGreyF2F5F7};`
> > I think they are good contrasting colors for our theme, considering our theme stays consistent, LGTM!
> 
> @LibenHailu yes, I don't think that `props.theme.grey191919ToGreyF2F5F7` is a default theme that we're using in our site

In the deployed version check it out it looks close.

File: src/sections/Home/Playground-home/index.js (hunk 1 above)
Comment (ashok-2003) [reply src/sections/Home/Playground-home/index.js]: Ah, sorry — I think the SVG was supposed to merge with the background to make it look seamless. Thanks for pointing that out. And yes, the main issue was with the text, which I’ve already addressed. I’ll go ahead and revert the background color changes.

https://github.com/user-attachments/assets/b94112e9-c2d5-4d80-92e1-a64efb5bb164

File: src/sections/Home/Playground-home/index.js (hunk 2 above)
Comment (ashok-2003) [reply src/sections/Home/Playground-home/index.js]: Got it, thanks for the suggestion! I’ll make sure to keep indentation or formatting fixes in a separate commit towards the end — makes total sense for cleaner reviews. 🙌

**Comment by ashok-2003** [comment]
@LibenHailu Yeah, I later realized that a contrasting background might actually work better. Initially, I was aiming for a more blended look, but I’ll revert it back to the original for better clarity.

@M-DEV-1 Just to clarify, `props.theme.grey191919ToGreyF2F5F7` is used as the main background color for that container — I took inspiration from there.

**Comment by l5io** [comment]
🚀 Preview for commit bd385c80cddaece0c4ff3a017ce73ea4a1cbd4cf at: https://68407bd8d2d571565f5b4084--layer5.netlify.app

**Comment by vishalvivekm** [comment]
@ashok-2003 will you please be reverting any formatting, white spaces as other reviews have noted as well?

**Comment by vishalvivekm** [comment]
@ashok-2003 
Let's also discuss this during the website call today at 7 AM CT | 5:30 PM IST.

Add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk), if you would :)

**Comment by l5io** [comment]
🚀 Preview for commit ec02150fd91858be3971d8c0d6113d59db5950c1 at: https://684662cf9928c8757983814e--layer5.netlify.app

**Comment by ashok-2003** [comment]
@vishalvivekm, thank you for your review. Reverting those formatting changes may likely cause issues, as discussed in the meetings. Are these the required changes, or is there anything more I’m expected to do?

**Comment by LibenHailu** [comment]
Hi @ashok-2003, as discussed on the sites meeting let's fix format issues if there are any, you can use `npm run lint` before committing your changes, it will fix lint issue if there are any, after that please re-request review. other than that LGTM!

File: src/sections/Home/Playground-home/index.js [hunk 3]
```diff
@@ -106,7 +106,7 @@ const ViewsSectionWrapper = styled.div`
       /* max-width: 90%; */
       padding-bottom: 2%;
     }
-  }
```
Comment (ashok-2003) [inline src/sections/Home/Playground-home/index.js:109]: This was causing the issue where the Card component wasn't rendering the color according to the background.

**Comment by ashok-2003** [comment]
@LibenHailu, thank you for the suggestion. Unfortunately, npm run lint doesn’t work for me. After a lot of head-banging, I’ve found the main and minimal changes that are required. Are we good to go? @M-DEV-1, @vishalvivekm

**Comment by LibenHailu** [comment]
> @LibenHailu, thank you for the suggestion. Unfortunately, npm run lint doesn’t work for me. After a lot of head-banging, I’ve found the main and minimal changes that are required. Are we good to go? @M-DEV-1, @vishalvivekm

@ashok-2003  Please feel free to share the error logs on slack with me if the issue persists. I am not seeing the deployment link tho.

**Comment by M-DEV-1** [comment]
@ashok-2003 @LibenHailu i suppose this is completed?

**Comment by ashok-2003** [comment]
@M-DEV-1 , Yes, I've implemented the necessary changes to resolve the issue, and I've ensured no other linting rules were modified, as discussed in the meeting.

**Comment by vr-varad** [comment]
@vishalvivekm Please Merge.

**Comment by l5io** [comment]
🚀 Preview for commit 3d072e682e8fcb70e18cc9cbba29c4e37dc45581 at: https://685e8b1887e4deb59d1bce70--layer5.netlify.app

**Review by vishalvivekm — APPROVED** [review]
Good work
