### PR TITLE
Fix 404s v

### LINKED ISSUE #6390: fix 404s links
### Current Behavior

Google Search Console has identified that some pages on the site are not being indexed due to `Not found (404)` errors.
> [!IMPORTANT]
> We need to evaluate whether these links should be fixed, redirected, or simply ignored (e.g., if they result from incorrect user searches).

URL | Last crawled
-- | --
https://layer5.io/articles/kubernetes/management-of-kubernetes |
https://layer5.io/cloud-native-management/meshmap/collaborate/peer-reviews.html | ########
https://layer5.io/community/members/matthieu-ervin | ########
https://layer5.io/whiteboard | ########
https://layer5.io/solutions/devrel-platform-for-kubernetes-and-cloudnative-content.html | ########
https://layer5.io/cloud-native-management/meshery/integrations/helm | ########
https://layer5.io/resources/case-study/hpes-adoption-of-meshery-and-meshmap | ########
https://layer5.io/cloud-native-management/meshery/integrations/cert-manager-csi-driver-cacerts.html | ########
https://layer5.io/community/events/project-office-hours-service-mesh-performance-at-kubecon-na-2021 | ########
https://layer5.io/cloud-native-management/meshery/integrations/serverless-devs | ########
https://layer5.io/cloud-native-management/meshmap/visualize | ########
https://layer5.io/blog/landscape/layer5-landscape-spectrums-revisited | ########
https://layer5.io/blog/landscape/hacktoberfest-2019-heating-up | ########
https://layer5.io/static/layer5-          solving-the-service-mesh-adopterâ€™s-dilemma-201fb82e14bc089fdd3ffa7d7c3ad9d3.pdf | ########
https://layer5.io/solutions | ########
https://layer5.io/community/events/meet-the-meshery-maintainers-at-kubecon-na-2021 | ########
https://layer5.io/community/events/kubecon-cloudnativecon-eu-virtual-2021 | ########
https://layer5.io/cloud-native-management/meshmap/design | ########
https://layer5.io/projects/sistent/components/box.html | ########
https://layer5.io/blog/community/lfx-experience-at-layer5-pranav-singh | ########
https://layer5.io/resources/faq/internship-faqs.html.html | ########
https://layer5.io/project/sistent | ########
https://layer5.io/cloud-native-management/meshery/integrations/cert-manager-csi-driver-cacerts | ########
https://layer5.io/blog/tag/smp | ########
https://layer5.io/community/events/servicemeshcon-na-2021 | ########
https://layer5.io/cloud-native-management/meshery/integrations/argo | ########
https://layer5.io/blog/tag/news | ########
https://layer5.io/programs/hacktoberfest/2021/newcomer | ########
https://layer5.io/projects/sistent/components/text-input/code.html | ########
https://layer5.io/communiity/events | ########
https://layer5.io/community/managers | ########
https://layer5.io/projects/sistent/components/button.html | ########
https://layer5.io/learn/learning-paths.html/mastering-service-meshes-for-developers | ########
https://layer5.io/projects/sistent/components/text-input/guidance.html | ########
https://layer5.io/blog/service-mesh-specifications/pipelining-service-mesh-specifications | ########
https://layer5.io/cloud-native-management/meshery/integrations/epam-delivery-platform-edp-admin-console | ########
https://layer5.io/cloud-native-management/meshery/integrations/apache-shardingsphere-operator-charts | ########
https://layer5.io/projects/sistent/components/modal.html | ########
https://layer5.io/cloud-native-management/meshery/integrations/aws-api-gateway-operator | ########
https://layer5.io/blog/tag/lfx | ########
https://layer5.io/projects/sistent/components/text-input.html | ########
https://layer5.io/projects/sistent/components/button/guidance.html | ########
https://layer5.io/blog/tag/sca | ########
https://layer5.io/blog/category/istio | ########
https://layer5.io/blog/category/open-service-mesh | ########
https://layer5.io/community/meshmate | ########
https://layer5.io/news/layer5-and-hashicorp-launch-service-mesh-partnership | ########
https://layer5.io/gsoc/2019 | ########
https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/advance-concepts-of-service-mesh.html/istio/conclusion | ########
https://layer5.io/cloud-native-management/meshery/integrations/meshery-operator | ########
https://layer5.io/cloud-native-management/meshery/integrations/service-mesh-interface-smi.html | ########
https://layer5.io/blog/category/envoy | ########
https://layer5.io/cloud- | ########
https://layer5.io/cloud-native-management/kanvas/visualize.html | ########
https://layer5.io/blog/tag/meshery-open-source | ########
https://layer5.io/meshery   </a>éƒ½æ˜¯å¦‚æ­¤.éƒ¨ç½²ISTIOæˆ–å…¶ä»–æœåŠ¡ç½‘ç»œç»•è¿‡.</p><p   style= | ########
https://layer5.io/meshery </a>   <a href= | ########
https://layer5.io/cloud-native-management/meshmap/collaborate/peer-reviews | ########
https://layer5.io/cloud-native-management/meshery/integrations/fluid | ########
https://layer5.io/blog/service-mesh/layer5-landscape-spectrums-revisited | ########
https://layer5.io/blog/tag/opensource | ########
https://layer5.io/community/members/undefined | ########
https://layer5.io/learn-ng/mastering-meshery-istio | ########
https://layer5.io/cloud-native-management/meshmap/collaborate | ########
https://layer5.io/learn-ng/mastering-meshery-istio/introduction-to-service-meshes/istio/getting-started | ########
https://layer5.io/projects/service-mesh-performance-specification | ########
https://layer5.io/products/service-mesh-performance | ########
https://layer5.io/products/nighthawk | ########
https://layer5.io/cloud-native-management/meshery/integrations/kubevault-metrics.html.html | ########

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Description**

This PR fixes #6390

source: 
- community/mangers
- communiity/evnets

add redirects: 

- /blog/community/lfx-experience-at-layer5-pranav-singh
- /resources/case-study/hpes-adoption-of-meshery-and-meshmap
- /articles/kubernetes/management-of-kubernetes
- /blog/landscape/layer5-landscape-spectrums-revisited
- blog/landscape/hacktoberfest-2019-heating-up
- https://layer5.io/cloud-native-management/meshmap/collaborate/peer-reviews
- splat redirects: reroutes all requests from `/cloud-native-management/meshmap/*` to `/cloud-native-management/kanvas/*`
**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

File: gatsby-node.js [hunk 1]
```diff
@@ -341,6 +341,12 @@ exports.createPages = async ({ actions, graphql, reporter }) => {
     redirectInBrowser: true,
     isPermanent: true,
   });
+  createRedirect({
+  fromPath: "/cloud-native-management/meshmap/*",
+  toPath: "/cloud-native-management/kanvas/*",
```
Comment (vishalvivekm) [inline gatsby-node.js:346]:
```suggestion
  toPath: "/cloud-native-management/kanvas/:splat",
```

**Comment by l5io** [comment]
🚀 Preview for commit 79d245ec771014b8b023dd3427cbe4b6370f15e8 at: https://680f6b397af234754b0c021a--layer5.netlify.app

File: gatsby-node.js [hunk 2]
```diff
@@ -341,6 +341,12 @@ exports.createPages = async ({ actions, graphql, reporter }) => {
     redirectInBrowser: true,
     isPermanent: true,
   });
+  createRedirect({
+  fromPath: "/cloud-native-management/meshmap/design",
+  toPath: "/cloud-native-management/kanvas/design",
+  redirectInBrowser: true,
+  isPermanent: true,
+});
```
Comment (vishalvivekm) [inline gatsby-node.js:349]:
```suggestion
  createRedirect({
  fromPath: "/cloud-native-management/meshmap/design",
  toPath: "/cloud-native-management/kanvas/design",
  redirectInBrowser: true,
  isPermanent: true,
});

  createRedirect({
  fromPath: "/cloud-native-management/meshmap/collaborate/peer-reviews",
  toPath: "/cloud-native-management/kanvas/collaborate/peer-reviews",
  redirectInBrowser: true,
  isPermanent: true,
});
```

**Comment by l5io** [comment]
🚀 Preview for commit 722984b06393672caf2a896cf8e16790da5bc520 at: https://681896c362571053a09130b2--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit da031ace9969dd553d8471022ce3b374269bf4fd at: https://68189f92c9fe8a6d00dd888a--layer5.netlify.app
