### PR TITLE
fix : highlight active section when switching tabs

### LINKED ISSUE #6329: Sidebar Components Not Highlighting Properly When Switching Tabs
### Description
While navigating through different sections of a component (e.g., "Code" and "Guidance"), the sidebar does not update to highlight the currently active section. This creates confusion, as users are unable to visually track which section they are currently viewing.

### Expected Behavior
The sidebar should dynamically update to highlight the currently active section when navigating between different component subsections.

### Screenshots

https://github.com/user-attachments/assets/247e8251-5db1-44a8-a667-0be0e8fc25b3

### Environment:
- Host OS:
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by GARY121github**
**Description**

This PR fixes #6329 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: src/components/SistentNavigation/index.js [hunk 1]
```diff
@@ -139,7 +139,7 @@ const TOC = () => {
                         <Link
                           to={component.url}
                           className={`toc-sub-heading toc-sub-inline components-item ${
-                            location.pathname === component.url
+                            location.pathname.split("/")[4] === component.url.split("/")[4]
```
Comment (leecalcote) [inline src/components/SistentNavigation/index.js:142]: This will ALWAYS be "4"?

**Comment by l5io** [comment]
🚀 Preview for commit 35760488ca4e759d47582328b84f0761bf21aece at: https://67dc3dba972c6123efc1d699--layer5.netlify.app

File: src/components/SistentNavigation/index.js (hunk 1 above)
Comment (GARY121github) [reply src/components/SistentNavigation/index.js:142]: If we will not be changing the navigations of this website in the future then Yes.

Comment (leecalcote) [reply src/components/SistentNavigation/index.js:142]: This is fragile code.
