### PR TITLE
Crash fix for the site

### LINKED ISSUE #1713: [Meshery] Remove "+" from Performance Test Result count
**Current Behavior**
A statistic counter on the Meshery page used for # of tests run has a "+" sign next to it.

**Desired Behavior**
“+” can be removed on Meshery page for # of tests run, since it is now exact number that is retrieved from a remote endpoint.

Screen Shot 2021-03-22 at 9 16 09 AM
---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### LINKED ISSUE #1714: Site crash: statistic counter
**Description**
Recent updates to the statistic counter are causing the site to crash.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**
Avoid the use of `async` for fetch calls.

This PR fixes #1714, fixes #1713 

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

File: src/sections/Meshery/Features-Col/index.js [hunk 1]
```diff
@@ -55,7 +51,7 @@ const Features = () => {
                       duration={6}
                       separator=","
                       end={feature.count.value !== 0 ? feature.count.value : performanceCount }
-                      suffix={feature.count.description == "service meshes supported" ? "" : "+"} />
+                      suffix={feature.count.description == "users" ? "+" : ""} />
```
Comment (leecalcote) [inline src/sections/Meshery/Features-Col/index.js:54]: Did we have the wrong description before?

File: src/sections/Meshery/Features-Col/index.js [hunk 2]
```diff
@@ -12,15 +12,11 @@ import Counter from "../../../reusecore/Counter";
...
-  useEffect(async () => {
-    try {
-      const response = await fetch("https://meshery.layer5.io/result/total");
-      const json = await response.json();
-      setPerformanceCount(json.total_runs);
-    } catch(err) {
-      console.log(err);
-    }
-  }, [setPerformanceCount]);
+  useEffect(() => {
```
Comment (leecalcote) [inline src/sections/Meshery/Features-Col/index.js:15]: Looks good.

File: src/sections/Meshery/Features-Col/index.js (hunk 1 above)
Comment (Nikhil-Ladha) [reply src/sections/Meshery/Features-Col/index.js:54]: No, just restricted the use of `+` symbol to `users` count. While others don't have it.

Comment (leecalcote) [reply src/sections/Meshery/Features-Col/index.js:54]: Oh. 😃

**Review by leecalcote — APPROVED** [review]

**Comment by l5io** [comment]
🚀 Preview for commit 26a9879c7005e6452b63f9f6ff81c06260c2eab5 at: https://6058d495c448661595fd4cf6--layer5ng.netlify.app

**Comment by leecalcote** [comment]
Awesome. Thank you for taking care of this quickly.
