### PR TITLE
Fix: Eliminate two build warnings

### LINKED ISSUE #6846: [CI] Eliminate two build warnings
### Current Behavior
```
info Skipping creating page "/projects/sistent/components/icons/guidance" - file not found: "./src/sections/Projects/Sistent/components/icons/guidance.js"
info Skipping creating page "/projects/sistent/components/icons/code" - file not found: "./src/sections/Projects/Sistent/components/icons/code.js"
```

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by Rajesh-Nagarajan-11**
**Description**

This PR fixes #6846 
This PR addresses the build warnings caused by missing files in the sistent/components/icons directory.

Before : 
Screenshot from 2025-09-23 20-45-51

After : 
Screenshot from 2025-09-23 20-56-44

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Too fragile.

**Comment by l5io** [comment]
🚀 Preview for commit 4a040eb3ad0a1f390f2032485d990114387fb628 at: https://68d2c06d99a3d646bf7d8bef--layer5.netlify.app

**Comment by Rajesh-Nagarajan-11** [comment]
@leecalcote 
 - The build script now dynamically checks for the existence of each expected file before attempting to create a page.
- Pages are only created for files that actually exist, eliminating unnecessary build warnings and making the process more resilient to missing files.
- This approach is generalized and does not rely on hardcoded exceptions for specific components, making it easier to maintain and extend in the future.

**Comment by l5io** [comment]
🚀 Preview for commit db96801e9e3561ce96b006562eeba8747ccebb87 at: https://68d2c50d0012c15cdb604f2e--layer5.netlify.app

**Comment by aabidsofi19** [comment]
@Rajesh-Nagarajan-11 we shouldnt be doing this . rather than skipping files with broken or wrong imports we need to fix the import paths for these files or how we reference the components inside those files. this will only hide the problem under the rug and cause more pain

**Comment by Rajesh-Nagarajan-11** [comment]
@aabidsofi19  , We don't have and not needed Code.js and Guidance.js for Icons alone , that's a root cause of this issue. Could share your approach to solve this issue ?

**Comment by Rajesh-Nagarajan-11** [comment]
@leecalcote @aabidsofi19 Can i just replicate the overview content of icons to guidance and code as well ? Or else suggest me the approach, I don't know other than this  : (

**Comment by saurabhraghuvanshii** [comment]
@Rajesh-Nagarajan-11  We are using it inside index.js instead of creating a separate code.js, and the same applies to guidance.js. You can check it  [here](https://github.com/layer5io/layer5/blob/master/src/sections/Projects/Sistent/components/icons/index.js#L11-L25)

**Comment by Rajesh-Nagarajan-11** [comment]
@saurabhraghuvanshii I don't think that's  work , because build script searches for 3 file with their names. , instead of creating separate files ( code.js , guidance.js) , I kept all in index.js won't resolve the warning 

->> https://github.com/layer5io/layer5/blob/master/gatsby-node.js#L799-L803

**Comment by l5io** [comment]
🚀 Preview for commit 5b8ee53449b264fa95e778587facd3bec54568fb at: https://68d376f87aa058f0d2938fe8--layer5.netlify.app

**Comment by saurabhraghuvanshii** [comment]
@Rajesh-Nagarajan-11 I think instead of `returning null`, you should extract the available code and guidance from `index.js` and place them in their respective files.

**Comment by l5io** [comment]
🚀 Preview for commit 67d350372b69e9f71b5f9f4820a746279d3a1809 at: https://68f12d60831ec47d80a6d4dc--layer5.netlify.app

**Comment by Rajesh-Nagarajan-11** [comment]
Will update @saurabhraghuvanshii

**Comment by l5io** [comment]
🚀 Preview for commit 2b0b8637d594ef17183e04818894c17b55269a57 at: https://68f79c40b0c537683926be23--layer5.netlify.app

**Comment by saurabhraghuvanshii** [comment]
@Rajesh-Nagarajan-11 also put this section into code.js 
Screenshot From 2025-10-21 20-25-39

**Comment by l5io** [comment]
🚀 Preview for commit e7f6fb57e7c40a4b57834780a16dc7be871cecda at: https://68f7a8e52e8a879854d5e665--layer5.netlify.app

**Review by saurabhraghuvanshii — APPROVED** [review]
thanks @Rajesh-Nagarajan-11 lgtm

**Comment by saurabhraghuvanshii** [comment]
@leecalcote @aabidsofi19 can you review it once

**Comment by leecalcote** [comment]
> @leecalcote @aabidsofi19 can you review it once

You guys can handle this unto your own. Call in @sudhanshutech or others, if you need a third set of eyes.

File: src/sections/Projects/Sistent/components/icons/code.js [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+import TabButton from "../../../../../reusecore/Button";
+import { useStyledDarkMode } from "../../../../../theme/app/useStyledDarkMode";
+import { CodeBlock } from "../button/code-block";
+
+const codes = [
+  `  import {
+    SistentThemeProvider,
+    KubernetesIcon,
+    DesignIcon,
+  } from "@sistent/sistent";
```
Comment (sudhanshutech) [inline src/sections/Projects/Sistent/components/icons/code.js]: @Rajesh-Nagarajan-11 is this right directory? Isn't it is` @layer5/sistent`

Comment (Rajesh-Nagarajan-11) [reply src/sections/Projects/Sistent/components/icons/code.js]: Yes this is right @sistent/sistent

**Comment by saurabhraghuvanshii** [comment]
@Rajesh-Nagarajan-11  Please remove [these lines](https://github.com/layer5io/layer5/pull/6861/files#diff-f3fd71aea24da86c9356bec376eeac75ef46872223aff26ec4a5fd96dd646292R13-R29)
. You’ve already added them in code.js, so there’s no need to include them in both places.

**Comment by l5io** [comment]
🚀 Preview for commit c2cf65eef30a909e815d39a35a143eafb3b1425b at: https://68f89bea00e93e22545c1e2b--layer5.netlify.app

**Comment by saurabhraghuvanshii** [comment]
@Rajesh-Nagarajan-11 any updates?

**Comment by Rajesh-Nagarajan-11** [comment]
Will update

**Comment by l5io** [comment]
🚀 Preview for commit bb7b1f5a021d69a4a4cd95f8501f6044d485d0be at: https://6908a8cf640e350fe24ec424--layer5.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 9857fb429941c6f287008a9958291c854ccf0e47 at: https://6908b2c73713fb2de49a76cc--layer5.netlify.app

**Comment by saurabhraghuvanshii** [comment]
Thanks @Rajesh-Nagarajan-11  lgtm
